"use client";
/* eslint-disable @next/next/no-img-element */

import { useEffect, useRef, useState } from "react";
import QRCode from "qrcode";
import { NumberField, ResultGrid, SelectField, ToolFrame } from "./shared";

export function QrTool({name}:{name:string}){
  const [value,setValue]=useState("https://example.com");const [size,setSize]=useState("320");const [level,setLevel]=useState("M");const [url,setUrl]=useState("");const [error,setError]=useState("");
  useEffect(()=>{let active=true;QRCode.toDataURL(value||" ",{width:Number(size),margin:2,errorCorrectionLevel:level as "L"|"M"|"Q"|"H",color:{dark:"#171713",light:"#fffefa"}}).then((result)=>{if(active){setUrl(result);setError("");}}).catch((caught)=>{if(active)setError(caught instanceof Error?caught.message:"Could not create QR code.");});return()=>{active=false;};},[value,size,level]);
  return <ToolFrame title={name} status="PNG output"><div className="qr-layout"><div className="qr-preview">{url&&<img src={url} alt="Generated QR code" />}</div><div><label className="field"><span>Text or URL</span><textarea rows={6} value={value} onChange={(event)=>setValue(event.target.value)} /></label><div className="field-grid qr-options"><SelectField label="Size" value={size} onChange={setSize} options={[["192","192 px"],["320","320 px"],["512","512 px"],["1024","1024 px"]]} /><SelectField label="Error correction" value={level} onChange={setLevel} options={[["L","Low"],["M","Medium"],["Q","Quartile"],["H","High"]]} /></div>{error&&<div className="error-output">{error}</div>}{url&&<a className="plain-button primary-button" href={url} download="qr-code.png">Download QR code</a>}</div></div><p className="tool-caution">Test the finished code with more than one camera before printing. Higher error correction helps damaged codes but makes the pattern denser.</p></ToolFrame>;
}

function loadBitmap(file:File){return createImageBitmap(file);}
function canvasBlob(canvas:HTMLCanvasElement,type:string,quality?:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob((blob)=>blob?resolve(blob):reject(new Error("Image export failed.")),type,quality));}

export function ImageUtilityTool({name,slug}:{name:string;slug:string}){
  const canvasRef=useRef<HTMLCanvasElement>(null);const [file,setFile]=useState<File|null>(null);const [width,setWidth]=useState("1200"),[height,setHeight]=useState("800"),[quality,setQuality]=useState("82"),[background,setBackground]=useState("#ffffff"),[lock,setLock]=useState(true),[sourceSize,setSourceSize]=useState<[number,number]>([0,0]),[result,setResult]=useState<{url:string;size:number;width:number;height:number}|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const choose=async(next:File)=>{setFile(next);if(result)URL.revokeObjectURL(result.url);setResult(null);setError("");try{const bitmap=await loadBitmap(next);setSourceSize([bitmap.width,bitmap.height]);setWidth(String(bitmap.width));setHeight(String(bitmap.height));bitmap.close();}catch{setFile(null);setSourceSize([0,0]);setError("The browser could not decode this image.");}};
  const updateWidth=(next:string)=>{setWidth(next);if(lock&&sourceSize[0])setHeight(String(Math.max(1,Math.round(Number(next)*sourceSize[1]/sourceSize[0]))));}; const updateHeight=(next:string)=>{setHeight(next);if(lock&&sourceSize[1])setWidth(String(Math.max(1,Math.round(Number(next)*sourceSize[0]/sourceSize[1]))));};
  const run=async()=>{if(!file)return;setBusy(true);setError("");try{const bitmap=await loadBitmap(file);const canvas=canvasRef.current;if(!canvas)throw new Error("Canvas unavailable.");let outWidth=bitmap.width,outHeight=bitmap.height;if(slug==="image-resizer"){outWidth=Math.max(1,Math.floor(Number(width))||1);outHeight=Math.max(1,Math.floor(Number(height))||1);}if(outWidth>16384||outHeight>16384||outWidth*outHeight>100_000_000){bitmap.close();throw new Error("Choose dimensions below 16,384 px and 100 megapixels.");}canvas.width=outWidth;canvas.height=outHeight;const context=canvas.getContext("2d");if(!context){bitmap.close();throw new Error("Canvas unavailable.");}const outputType=slug==="jpg-to-png-converter"?"image/png":"image/jpeg";if(outputType==="image/jpeg"){context.fillStyle=background;context.fillRect(0,0,outWidth,outHeight);}context.drawImage(bitmap,0,0,outWidth,outHeight);bitmap.close();const blob=await canvasBlob(canvas,outputType,Math.min(1,Math.max(.01,Number(quality)/100||.82)));if(result)URL.revokeObjectURL(result.url);setResult({url:URL.createObjectURL(blob),size:blob.size,width:outWidth,height:outHeight});}catch(caught){setError(caught instanceof Error?caught.message:"Image processing failed.");}finally{setBusy(false);}};
  const accept=slug==="jpg-to-png-converter"?"image/jpeg,.jpg,.jpeg":slug==="png-to-jpg-converter"?"image/png,.png":slug==="webp-to-jpg-converter"?"image/webp,.webp":"image/*"; const ext=slug==="jpg-to-png-converter"?"png":"jpg";
  return <ToolFrame title={name} status="processed locally"><label className="file-drop compact-drop"><span className="file-drop-title">{file?file.name:"Choose an image"}</span><span className="file-drop-detail">{accept.includes("jpeg")?"JPEG input":accept.includes("png")?"PNG input":accept.includes("webp")?"WebP input":"JPEG, PNG, WebP, or browser-readable image"}</span><input type="file" accept={accept} onChange={(event)=>{const next=event.target.files?.[0];if(next)choose(next);}} /><span className="plain-button file-button">Browse files</span></label>{file&&<div className="image-settings">{slug==="image-resizer"&&<><div className="field-grid"><NumberField label="Output width" value={width} onChange={updateWidth} min={1} max={16384} step={1} suffix="px" /><NumberField label="Output height" value={height} onChange={updateHeight} min={1} max={16384} step={1} suffix="px" /></div><label className="single-check"><input type="checkbox" checked={lock} onChange={(event)=>setLock(event.target.checked)} /> Preserve aspect ratio</label></>}{slug!=="jpg-to-png-converter"&&<div className="field-grid"><NumberField label="JPEG quality" value={quality} onChange={setQuality} min={1} max={100} step={1} suffix="%" />{slug==="png-to-jpg-converter"&&<label className="field"><span>Transparent background</span><input type="color" value={background} onChange={(event)=>setBackground(event.target.value)} /></label>}</div>}<button className="plain-button primary-button" type="button" disabled={busy} onClick={run}>{busy?"Processing…":slug.includes("converter")?"Convert image":slug==="image-resizer"?"Resize image":"Compress image"}</button></div>}{error&&<div className="error-output">{error}</div>}<canvas ref={canvasRef} hidden />{result&&<div className="image-output"><img src={result.url} alt="Processed image preview" /><ResultGrid values={[["Original",`${sourceSize[0]} × ${sourceSize[1]} px`],["Output",`${result.width} × ${result.height} px`],["Original size",file?`${(file.size/1024).toFixed(1)} KB`:""],["Output size",`${(result.size/1024).toFixed(1)} KB`],["Change",file?`${Math.round((1-result.size/file.size)*100)}%`:""]]} /><a className="plain-button primary-button" href={result.url} download={`converted-image.${ext}`}>Download {ext.toUpperCase()}</a></div>}<p className="tool-caution">Canvas export removes most embedded metadata. Keep the original file if EXIF, color profile, or editing history matters.</p></ToolFrame>;
}

function downloadBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function PdfMergerTool({name}:{name:string}){const [files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const merge=async()=>{if(!files.length)return;setBusy(true);setMessage("");try{const {PDFDocument}=await import("pdf-lib");const output=await PDFDocument.create();let pages=0;for(const file of files){const source=await PDFDocument.load(await file.arrayBuffer());const copied=await output.copyPages(source,source.getPageIndices());copied.forEach((page)=>output.addPage(page));pages+=copied.length;}const bytes=await output.save();downloadBlob(new Blob([bytes.buffer as ArrayBuffer],{type:"application/pdf"}),"merged.pdf");setMessage(`Merged ${files.length} files and ${pages} pages.`);}catch(caught){setMessage(caught instanceof Error?caught.message:"Could not merge these PDFs.");}finally{setBusy(false);}};return <ToolFrame title={name} status="no upload"><label className="file-drop compact-drop"><span className="file-drop-title">Choose PDF files</span><span className="file-drop-detail">Select two or more in the order your file picker provides</span><input type="file" accept="application/pdf,.pdf" multiple onChange={(event)=>setFiles(Array.from(event.target.files||[]))} /><span className="plain-button file-button">Browse PDFs</span></label>{files.length>0&&<ol className="selected-files">{files.map((file)=><li key={`${file.name}-${file.size}`}>{file.name}<span>{(file.size/1024).toFixed(1)} KB</span></li>)}</ol>}<button className="plain-button primary-button" type="button" disabled={busy||files.length<2} onClick={merge}>{busy?"Merging…":"Merge and download"}</button>{message&&<div className="notice-output">{message}</div>}</ToolFrame>;}

function parsePages(value:string,total:number){const pages=new Set<number>();for(const part of value.split(",")){const trimmed=part.trim();if(!trimmed)continue;if(trimmed.includes("-")){const [start,end]=trimmed.split("-").map(Number);for(let page=start;page<=end;page++)if(page>=1&&page<=total)pages.add(page-1);}else{const page=Number(trimmed);if(page>=1&&page<=total)pages.add(page-1);}}return [...pages].sort((a,b)=>a-b);}
export function PdfSplitterTool({name}:{name:string}){const [file,setFile]=useState<File|null>(null),[range,setRange]=useState("1-3"),[pages,setPages]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const choose=async(next:File)=>{setFile(next);setMessage("");try{const {PDFDocument}=await import("pdf-lib");const doc=await PDFDocument.load(await next.arrayBuffer());setPages(doc.getPageCount());setRange(`1-${Math.min(3,doc.getPageCount())}`);}catch(caught){setMessage(caught instanceof Error?caught.message:"Could not open this PDF.");}};const split=async()=>{if(!file)return;setBusy(true);setMessage("");try{const {PDFDocument}=await import("pdf-lib");const source=await PDFDocument.load(await file.arrayBuffer());const selected=parsePages(range,source.getPageCount());if(!selected.length)throw new Error("No valid pages are selected.");const output=await PDFDocument.create();const copied=await output.copyPages(source,selected);copied.forEach((page)=>output.addPage(page));const bytes=await output.save();downloadBlob(new Blob([bytes.buffer as ArrayBuffer],{type:"application/pdf"}),"extracted-pages.pdf");setMessage(`Extracted ${selected.length} of ${source.getPageCount()} pages.`);}catch(caught){setMessage(caught instanceof Error?caught.message:"Could not split this PDF.");}finally{setBusy(false);}};return <ToolFrame title={name} status="extract page ranges"><label className="file-drop compact-drop"><span className="file-drop-title">{file?file.name:"Choose a PDF"}</span><span className="file-drop-detail">The file stays in this browser tab</span><input type="file" accept="application/pdf,.pdf" onChange={(event)=>{const next=event.target.files?.[0];if(next)choose(next);}} /><span className="plain-button file-button">Browse PDF</span></label>{file&&<><label className="field"><span>Pages to extract {pages?`(1–${pages})`:""}</span><input value={range} onChange={(event)=>setRange(event.target.value)} placeholder="1-3, 5, 8-10" /></label><button className="plain-button primary-button" type="button" disabled={busy} onClick={split}>{busy?"Extracting…":"Extract and download"}</button></>}{message&&<div className={message.startsWith("Extracted")?"notice-output":"error-output"}>{message}</div>}<p className="tool-caution">Encrypted or damaged PDFs may not open. The downloaded file contains the selected pages in their original order.</p></ToolFrame>;}
