"use client";

import { useMemo, useState } from "react";
import { ActionRow, copyText, NumberField, ResultGrid, secureRandomInt, SelectField, ToolFrame } from "./shared";
import { addUtcYearsClamped, calendarDifference, localDateTimeInput, parseDateOnly } from "./date-math";

const permissionBits = [
  ["Owner read", 0o400], ["Owner write", 0o200], ["Owner execute", 0o100],
  ["Group read", 0o040], ["Group write", 0o020], ["Group execute", 0o010],
  ["Others read", 0o004], ["Others write", 0o002], ["Others execute", 0o001],
] as const;

export function ChmodTool({ name }: { name: string }) {
  const [bits, setBits] = useState(0o755);
  const octal = bits.toString(8).padStart(3, "0");
  const symbolic = [0o400,0o200,0o100,0o040,0o020,0o010,0o004,0o002,0o001].map((bit, index) => bits & bit ? "rwx"[index % 3] : "-").join("");
  const output = `Octal: ${octal}\nSymbolic: ${symbolic}\nCommand: chmod ${octal} filename`;
  return <ToolFrame title={name} status="updates live"><div className="permission-grid">{permissionBits.map(([label, bit]) => <label key={label}><input type="checkbox" checked={!!(bits & bit)} onChange={(event) => setBits((current) => event.target.checked ? current | bit : current & ~bit)} /><span>{label}</span></label>)}</div><div className="big-code wrap-code"><code>chmod {octal} filename</code><button type="button" onClick={() => copyText(`chmod ${octal} filename`)}>Copy</button></div><ResultGrid values={[["Octal", octal], ["Symbolic", symbolic], ["Owner", symbolic.slice(0,3)], ["Group", symbolic.slice(3,6)], ["Others", symbolic.slice(6,9)]]} /><ActionRow output={output} filename="chmod-permissions.txt" /></ToolFrame>;
}

function ipToNumber(ip: string) { const parts = ip.trim().split("."); if (parts.length !== 4 || parts.some((part) => !/^\d+$/.test(part) || Number(part) > 255)) throw new Error("Enter a valid IPv4 address."); return parts.reduce((value, part) => (value * 256 + Number(part)) >>> 0, 0); }
function numberToIp(value: number) { return [24,16,8,0].map((shift) => (value >>> shift) & 255).join("."); }
function networkInfo(ip: string, prefix: number) { if (!Number.isInteger(prefix) || prefix < 0 || prefix > 32) throw new Error("CIDR prefix must be a whole number from 0 to 32."); const address = ipToNumber(ip); const mask = prefix === 0 ? 0 : (0xffffffff << (32 - prefix)) >>> 0; const network = (address & mask) >>> 0; const broadcast = (network | (~mask >>> 0)) >>> 0; const total = 2 ** (32 - prefix); return { mask, network, broadcast, total }; }

export function NetworkTool({ name, subnet = false }: { name: string; subnet?: boolean }) {
  const [ip, setIp] = useState("192.168.1.42"); const [prefix, setPrefix] = useState("24"); const [newPrefix, setNewPrefix] = useState("27");
  const result = useMemo(() => { try { const basePrefix = Number(prefix); const base = networkInfo(ip, basePrefix); const target = subnet ? Number(newPrefix) : basePrefix; if (!Number.isInteger(target) || target < basePrefix || target > 32) throw new Error(`New subnet prefix must be a whole number from ${basePrefix} to 32.`); const subnetCount = 2 ** (target - basePrefix); const size = 2 ** (32 - target); const ranges = Array.from({ length: Math.min(subnetCount, 64) }, (_, index) => { const start = (base.network + index * size) >>> 0; return `${numberToIp(start)}/${target}   ${numberToIp(start)} – ${numberToIp((start + size - 1) >>> 0)}`; }); return { error: "", info: base, target, subnetCount, ranges }; } catch (error) { return { error: error instanceof Error ? error.message : "Invalid network", info: null, target: 0, subnetCount: 0, ranges: [] as string[] }; } }, [ip, prefix, newPrefix, subnet]);
  return <ToolFrame title={name} status="IPv4"><div className="field-grid three-up"><label className="field"><span>IPv4 address</span><input value={ip} onChange={(event) => setIp(event.target.value)} /></label><NumberField label="CIDR prefix" value={prefix} onChange={setPrefix} min={0} step={1} suffix="bits" />{subnet && <NumberField label="New subnet prefix" value={newPrefix} onChange={setNewPrefix} min={Number(prefix)} step={1} suffix="bits" />}</div>{result.error ? <div className="error-output">{result.error}</div> : result.info && <><ResultGrid values={[["Network", `${numberToIp(result.info.network)}/${prefix}`], ["Subnet mask", numberToIp(result.info.mask)], ["Broadcast", numberToIp(result.info.broadcast)], ["Total addresses", result.info.total.toLocaleString()], ["Usable hosts", Math.max(0, result.info.total - 2).toLocaleString()], ...(subnet ? [["New subnets", result.subnetCount.toLocaleString()] as [string,string]] : [])]} />{subnet && <textarea className="mono-input output-area network-ranges" value={result.ranges.join("\n")} rows={Math.min(14, result.ranges.length + 1)} readOnly />}<ActionRow output={subnet ? result.ranges.join("\n") : `Network: ${numberToIp(result.info.network)}/${prefix}\nMask: ${numberToIp(result.info.mask)}\nBroadcast: ${numberToIp(result.info.broadcast)}\nAddresses: ${result.info.total}`} filename={subnet ? "subnets.txt" : "cidr-result.txt"} /></>}</ToolFrame>;
}

export function UtmTool({ name }: { name: string }) {
  const [values, setValues] = useState({ url: "https://example.com/landing", source: "newsletter", medium: "email", campaign: "summer_launch", term: "", content: "button_a" });
  const update = (key: keyof typeof values, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const result = useMemo(() => { try { const url = new URL(values.url); const map = { utm_source: values.source, utm_medium: values.medium, utm_campaign: values.campaign, utm_term: values.term, utm_content: values.content }; Object.entries(map).forEach(([key, value]) => { if (value) url.searchParams.set(key, value); }); return { value: url.toString(), error: "" }; } catch { return { value: "", error: "Enter a complete URL including https://" }; } }, [values]);
  return <ToolFrame title={name} status="properly encoded"><div className="field-grid">{[["url","Destination URL"],["source","Campaign source"],["medium","Campaign medium"],["campaign","Campaign name"],["term","Paid keyword (optional)"],["content","Content variant (optional)"]].map(([key,label]) => <label className="field" key={key}><span>{label}</span><input value={values[key as keyof typeof values]} onChange={(event) => update(key as keyof typeof values, event.target.value)} /></label>)}</div>{result.error ? <div className="error-output">{result.error}</div> : <><div className="big-code wrap-code"><code>{result.value}</code><button type="button" onClick={() => copyText(result.value)}>Copy</button></div><ActionRow output={result.value} filename="utm-link.txt" /></>}<p className="tool-caution">Use consistent lowercase naming conventions so analytics reports do not split the same source into multiple rows.</p></ToolFrame>;
}

const ambiguous = new Set(["0","O","o","1","l","I"]);
export function PasswordTool({ name }: { name: string }) {
  const [length, setLength] = useState("20"); const [sets, setSets] = useState({ lower: true, upper: true, numbers: true, symbols: true, ambiguous: false }); const [count, setCount] = useState("8"); const [passwords, setPasswords] = useState<string[]>([]);
  const generate = () => { let chars = `${sets.lower ? "abcdefghijklmnopqrstuvwxyz" : ""}${sets.upper ? "ABCDEFGHIJKLMNOPQRSTUVWXYZ" : ""}${sets.numbers ? "0123456789" : ""}${sets.symbols ? "!@#$%^&*()-_=+[]{};:,.?" : ""}`; if (!sets.ambiguous) chars = [...chars].filter((char) => !ambiguous.has(char)).join(""); if (!chars) return setPasswords([]); const amount = Math.min(50, Math.max(1, Math.floor(Number(count)) || 1)); const size = Math.min(128, Math.max(4, Math.floor(Number(length)) || 20)); setPasswords(Array.from({ length: amount }, () => Array.from({ length: size }, () => chars[secureRandomInt(chars.length)]).join(""))); };
  return <ToolFrame title={name} status="Web Crypto randomness"><div className="field-grid"><NumberField label="Password length" value={length} onChange={setLength} min={4} step={1} /><NumberField label="How many" value={count} onChange={setCount} min={1} step={1} /></div><div className="option-checks">{[["lower","Lowercase"],["upper","Uppercase"],["numbers","Numbers"],["symbols","Symbols"],["ambiguous","Allow ambiguous 0/O/1/l"]].map(([key,label]) => <label key={key}><input type="checkbox" checked={sets[key as keyof typeof sets]} onChange={(event) => setSets((current) => ({ ...current, [key]: event.target.checked }))} />{label}</label>)}</div><button className="plain-button primary-button" type="button" onClick={generate}>Generate passwords</button>{passwords.length > 0 && <><textarea className="mono-input output-area" value={passwords.join("\n")} rows={Math.min(14,passwords.length+1)} readOnly /><ActionRow output={passwords.join("\n")} filename="passwords.txt" /></>}<p className="tool-caution">Generated locally with the browser’s cryptographic random source. Store important passwords in a trusted password manager.</p></ToolFrame>;
}

export function AgeTool({ name }: { name: string }) {
  const [birth, setBirth] = useState("1995-01-01"); const [asOf, setAsOf] = useState(() => new Date().toISOString().slice(0,10));
  const result = useMemo(() => { const start = parseDateOnly(birth); const end = parseDateOnly(asOf); if (!start || !end || end < start) return null; const { years, months, days } = calendarDifference(start, end); let next = addUtcYearsClamped(start, end.getUTCFullYear() - start.getUTCFullYear()); if (next < end) next = addUtcYearsClamped(start, end.getUTCFullYear() - start.getUTCFullYear() + 1); const totalDays = Math.round((end.getTime()-start.getTime())/86400000); return { years, months, days, totalDays, next, until: Math.round((next.getTime()-end.getTime())/86400000) }; }, [birth,asOf]);
  return <ToolFrame title={name} status="calendar exact"><div className="field-grid"><label className="field"><span>Date of birth</span><input type="date" value={birth} onChange={(event) => setBirth(event.target.value)} /></label><label className="field"><span>Age on date</span><input type="date" value={asOf} onChange={(event) => setAsOf(event.target.value)} /></label></div>{result ? <ResultGrid values={[["Exact age", `${result.years} years, ${result.months} months, ${result.days} days`], ["Total months", String(result.years*12+result.months)], ["Total days", result.totalDays.toLocaleString()], ["Next birthday", result.next.toLocaleDateString("en-US", { timeZone: "UTC" })], ["Days until next birthday", String(result.until)]]} /> : <div className="error-output">Enter a valid birth date before the comparison date.</div>}</ToolFrame>;
}

type UnitGroup = { base: string; units: Record<string, { label: string; toBase: (value: number) => number; fromBase: (value: number) => number }> };
const linear = (factor: number) => ({ toBase: (value: number) => value * factor, fromBase: (value: number) => value / factor });
const groups: Record<string, UnitGroup> = {
  length: { base: "m", units: { m: { label: "Meters", ...linear(1) }, km: { label: "Kilometers", ...linear(1000) }, cm: { label: "Centimeters", ...linear(.01) }, mm: { label: "Millimeters", ...linear(.001) }, in: { label: "Inches", ...linear(.0254) }, ft: { label: "Feet", ...linear(.3048) }, yd: { label: "Yards", ...linear(.9144) }, mi: { label: "Miles", ...linear(1609.344) } } },
  weight: { base: "kg", units: { kg: { label: "Kilograms", ...linear(1) }, g: { label: "Grams", ...linear(.001) }, lb: { label: "Pounds", ...linear(.45359237) }, oz: { label: "Ounces", ...linear(.028349523) }, ton: { label: "US tons", ...linear(907.18474) } } },
  temperature: { base: "c", units: { c: { label: "Celsius", toBase: (v) => v, fromBase: (v) => v }, f: { label: "Fahrenheit", toBase: (v) => (v-32)*5/9, fromBase: (v) => v*9/5+32 }, k: { label: "Kelvin", toBase: (v) => v-273.15, fromBase: (v) => v+273.15 } } },
  volume: { base: "l", units: { l: { label: "Liters", ...linear(1) }, ml: { label: "Milliliters", ...linear(.001) }, gal: { label: "US gallons", ...linear(3.785411784) }, qt: { label: "US quarts", ...linear(.946352946) }, cup: { label: "US cups", ...linear(.2365882365) }, floz: { label: "US fluid ounces", ...linear(.0295735296) } } },
  speed: { base: "mps", units: { mps: { label: "Meters/second", ...linear(1) }, kph: { label: "Kilometers/hour", ...linear(1/3.6) }, mph: { label: "Miles/hour", ...linear(.44704) }, knot: { label: "Knots", ...linear(.514444) } } },
};

export function UnitTool({ name }: { name: string }) {
  const [group,setGroup]=useState("length"); const [from,setFrom]=useState("m"); const [to,setTo]=useState("ft"); const [value,setValue]=useState("1"); const unitGroup=groups[group];
  const changeGroup=(next:string)=>{setGroup(next);const keys=Object.keys(groups[next].units);setFrom(keys[0]);setTo(keys[1]||keys[0]);}; const result=unitGroup.units[to].fromBase(unitGroup.units[from].toBase(Number(value)||0));
  return <ToolFrame title={name} status="common units"><div className="field-grid"><SelectField label="Measurement" value={group} onChange={changeGroup} options={Object.keys(groups).map((key)=>[key,key.charAt(0).toUpperCase()+key.slice(1)])} /><NumberField label="Value" value={value} onChange={setValue} /><SelectField label="From" value={from} onChange={setFrom} options={Object.entries(unitGroup.units).map(([key,unit])=>[key,unit.label])} /><SelectField label="To" value={to} onChange={setTo} options={Object.entries(unitGroup.units).map(([key,unit])=>[key,unit.label])} /></div><div className="conversion-result"><strong>{Number(value)||0} {unitGroup.units[from].label}</strong><span>=</span><strong>{result.toLocaleString("en-US",{maximumFractionDigits:10})} {unitGroup.units[to].label}</strong></div><ActionRow output={`${Number(value)||0} ${unitGroup.units[from].label} = ${result} ${unitGroup.units[to].label}`} filename="unit-conversion.txt" /></ToolFrame>;
}

export function RandomNumberTool({ name }: { name: string }) {
  const [min,setMin]=useState("1"),[max,setMax]=useState("100"),[count,setCount]=useState("10"),[unique,setUnique]=useState(true),[values,setValues]=useState<number[]>([]),[error,setError]=useState("");
  const generate=()=>{const low=Math.ceil(Number(min)),high=Math.floor(Number(max)),amount=Math.min(1000,Math.max(1,Math.floor(Number(count))||1));setError("");if(!Number.isSafeInteger(low)||!Number.isSafeInteger(high))return setError("Minimum and maximum must be safe whole numbers.");if(high<low)return setError("Maximum must be greater than or equal to minimum.");const range=high-low+1;if(!Number.isSafeInteger(range)||range>2**53)return setError("The selected range is too large for exact browser-safe integers.");if(unique&&amount>range)return setError(`Only ${range.toLocaleString()} unique values exist in this range.`);const output:number[]=[];while(output.length<amount){const value=low+secureRandomInt(range);if(!unique||!output.includes(value))output.push(value);}setValues(output);};
  return <ToolFrame title={name} status="cryptographic randomness"><div className="field-grid three-up"><NumberField label="Minimum" value={min} onChange={setMin} step={1} /><NumberField label="Maximum" value={max} onChange={setMax} step={1} /><NumberField label="How many" value={count} onChange={setCount} min={1} step={1} /></div><label className="single-check"><input type="checkbox" checked={unique} onChange={(event)=>setUnique(event.target.checked)} /> Require unique numbers</label><button className="plain-button primary-button" type="button" onClick={generate}>Generate numbers</button>{error&&<div className="error-output">{error}</div>}{values.length>0&&!error&&<><div className="number-chips">{values.map((value,index)=><span key={`${value}-${index}`}>{value}</span>)}</div><ActionRow output={values.join("\n")} filename="random-numbers.txt" /></>}</ToolFrame>;
}

const zones=["America/New_York","America/Chicago","America/Denver","America/Los_Angeles","America/Toronto","America/Sao_Paulo","Europe/London","Europe/Paris","Europe/Berlin","Africa/Johannesburg","Asia/Dubai","Asia/Kolkata","Asia/Singapore","Asia/Tokyo","Australia/Sydney","Pacific/Auckland","UTC"];
function zonedToDate(input:string,zone:string){const [date,time]=input.split("T");if(!date||!time)return new Date(NaN);const [year,month,day]=date.split("-").map(Number);const [hour,minute]=time.split(":").map(Number);let guess=Date.UTC(year,month-1,day,hour,minute);const formatter=new Intl.DateTimeFormat("en-CA",{timeZone:zone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"});for(let index=0;index<2;index++){const parts=Object.fromEntries(formatter.formatToParts(new Date(guess)).map((part)=>[part.type,part.value]));const shown=Date.UTC(Number(parts.year),Number(parts.month)-1,Number(parts.day),Number(parts.hour),Number(parts.minute));guess+=Date.UTC(year,month-1,day,hour,minute)-shown;}return new Date(guess);}
export function TimeZoneTool({name}:{name:string}){const [input,setInput]=useState(()=>localDateTimeInput());const [from,setFrom]=useState("America/New_York"),[to,setTo]=useState("Europe/London");const date=zonedToDate(input,from);const format=(zone:string)=>Number.isNaN(date.getTime())?"Invalid date":new Intl.DateTimeFormat("en-US",{timeZone:zone,dateStyle:"full",timeStyle:"long"}).format(date);const output=`${from}: ${format(from)}\n${to}: ${format(to)}\nUTC: ${Number.isNaN(date.getTime())?"Invalid date":date.toISOString()}`;return <ToolFrame title={name} status="DST aware"><div className="field-grid three-up"><label className="field"><span>Date and time</span><input type="datetime-local" value={input} onChange={(event)=>setInput(event.target.value)} /></label><SelectField label="From time zone" value={from} onChange={setFrom} options={zones.map((zone)=>[zone,zone.replaceAll("_"," ")])} /><SelectField label="To time zone" value={to} onChange={setTo} options={zones.map((zone)=>[zone,zone.replaceAll("_"," ")])} /></div><ResultGrid values={[["Source time",format(from)],["Converted time",format(to)],["UTC",Number.isNaN(date.getTime())?"Invalid date":date.toISOString()]]} /><ActionRow output={output} filename="time-zone-conversion.txt" /></ToolFrame>;}
