"use client";
/* eslint-disable @next/next/no-img-element */

import { useState } from "react";
import { ActionRow, NumberField, ResultGrid, ToolFrame } from "./shared";

function FilePicker({ accept, onFile, busy, hint }: { accept: string; onFile: (file: File) => void; busy: boolean; hint: string }) {
  return <label className={`file-drop compact-drop${busy ? " is-reading" : ""}`}><span className="file-drop-title">{busy ? "Working locally…" : "Choose a file"}</span><span className="file-drop-detail">{hint}</span><input type="file" accept={accept} disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; if (file) onFile(file); }} /><span className="plain-button file-button">Browse files</span></label>;
}

function csvCell(value: string) { return `"${value.replace(/"/g, '""')}"`; }

export function BankPdfTool({ name }: { name: string }) {
  const [busy, setBusy] = useState(false); const [csv, setCsv] = useState(""); const [message, setMessage] = useState("");
  const convert = async (file: File) => { setBusy(true); setCsv(""); setMessage(""); try { const bytes = new Uint8Array(await file.arrayBuffer()); const raw = new TextDecoder("latin1").decode(bytes); const textRuns = [...raw.matchAll(/[\x20-\x7E]{5,}/g)].map((match) => match[0].replace(/\\[nr]/g, " ").trim()).filter(Boolean); const rows: string[][] = []; const datePattern = /\b(?:\d{1,2}[\/-]\d{1,2}(?:[\/-]\d{2,4})?|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{1,2})\b/i; const amountPattern = /(?:[-+]?(?:\$|£|€)?\s?\d{1,3}(?:,\d{3})*\.\d{2})/g; for (const run of textRuns) { const date = run.match(datePattern)?.[0]; const amounts = run.match(amountPattern); if (date && amounts?.length) { const description = run.replace(datePattern, "").replace(amountPattern, " ").replace(/\s+/g, " ").trim(); rows.push([date, description, amounts[0], amounts[1] || ""]); } } const unique = rows.filter((row, index) => index === 0 || row.join("|") !== rows[index - 1].join("|")); if (!unique.length) throw new Error("No transaction rows were found. This statement may be scanned, encrypted, or store text in compressed drawing instructions."); const output = `Date,Description,Amount,Balance\n${unique.map((row) => row.map(csvCell).join(",")).join("\n")}`; setCsv(output); setMessage(`${unique.length} transaction-like rows found. Review dates, debit signs, and column alignment before importing.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not read this PDF."); } finally { setBusy(false); } };
  return <ToolFrame title={name} status="text-based PDFs"><FilePicker accept="application/pdf,.pdf" onFile={convert} busy={busy} hint="PDF statement · processed in this tab" />{message && <div className={csv ? "notice-output" : "error-output"}>{message}</div>}{csv && <><textarea className="mono-input output-area" value={csv} rows={14} readOnly /><ActionRow output={csv} filename="bank-statement.csv" /></>}<p className="tool-caution">Works best with text-based statements. Scanned pages need OCR. Always compare the CSV with the original before accounting or tax use.</p></ToolFrame>;
}

export function PsdTool({ name }: { name: string }) {
  const [busy, setBusy] = useState(false); const [url, setUrl] = useState(""); const [error, setError] = useState(""); const [info, setInfo] = useState<Array<[string, string]>>([]);
  const convert = async (file: File) => { setBusy(true); setError(""); if (url) URL.revokeObjectURL(url); setUrl(""); try { const { readPsd } = await import("ag-psd"); const psd = readPsd(await file.arrayBuffer(), { skipLayerImageData: true, skipThumbnail: true }); const canvas = psd.canvas; if (!canvas) throw new Error("This PSD does not contain a readable composite image preview."); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((value) => value ? resolve(value) : reject(new Error("PNG export failed.")), "image/png")); setUrl(URL.createObjectURL(blob)); setInfo([["File", file.name], ["Canvas", `${psd.width} × ${psd.height}px`], ["Layers", String(psd.children?.length || 0)], ["PNG size", `${(blob.size / 1024).toFixed(1)} KB`]]); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not read this PSD."); } finally { setBusy(false); } };
  return <ToolFrame title={name} status="flattened PNG"><FilePicker accept="image/vnd.adobe.photoshop,.psd" onFile={convert} busy={busy} hint="PSD file · composite preview exported locally" />{error && <div className="error-output">{error}</div>}{url && <div className="file-result"><img src={url} alt="Flattened PSD preview" /><ResultGrid values={info} /><a className="plain-button primary-button" href={url} download="converted-psd.png">Download PNG</a></div>}<p className="tool-caution">The PNG is a flattened visual export. Layers, adjustment data, editable text, masks, and Photoshop metadata are not preserved.</p></ToolFrame>;
}

function variableLength(value: number) { const bytes = [value & 0x7f]; while ((value >>= 7)) bytes.unshift((value & 0x7f) | 0x80); return bytes; }
function midiFile(notes: Array<{ note: number; ticks: number }>) { const track: number[] = [0, 0xff, 0x51, 3, 0x07, 0xa1, 0x20]; for (const item of notes) { track.push(0, 0x90, item.note, 88, ...variableLength(item.ticks), 0x80, item.note, 0); } track.push(0, 0xff, 0x2f, 0); const word = (value: number) => [(value >>> 8) & 255, value & 255]; const dword = (value: number) => [(value >>> 24) & 255, (value >>> 16) & 255, (value >>> 8) & 255, value & 255]; return new Uint8Array([0x4d,0x54,0x68,0x64,0,0,0,6,0,0,0,1,...word(480),0x4d,0x54,0x72,0x6b,...dword(track.length),...track]); }

export function Mp3MidiTool({ name }: { name: string }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [midiUrl, setMidiUrl] = useState(""); const [notes, setNotes] = useState<number[]>([]);
  const convert = async (file: File) => { setBusy(true); setMessage(""); setMidiUrl(""); try { const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext: typeof AudioContext }).webkitAudioContext; const context = new AudioContextClass(); const audio = await context.decodeAudioData(await file.arrayBuffer()); const source = audio.getChannelData(0); const windowSeconds = 0.18; const frame = Math.floor(audio.sampleRate * windowSeconds); const found: number[] = []; for (let start = 0; start + frame < source.length && found.length < 800; start += frame) { let crossings = 0, energy = 0; for (let i = start + 1; i < start + frame; i++) { energy += source[i] * source[i]; if ((source[i - 1] < 0 && source[i] >= 0) || (source[i - 1] >= 0 && source[i] < 0)) crossings++; } const rms = Math.sqrt(energy / frame); if (rms < 0.015) continue; const frequency = crossings * audio.sampleRate / (2 * frame); const note = Math.round(69 + 12 * Math.log2(frequency / 440)); if (note >= 24 && note <= 108 && found[found.length - 1] !== note) found.push(note); } await context.close(); if (!found.length) throw new Error("No clear single-note melody was detected. Try a louder, isolated vocal hum or instrument line."); const bytes = midiFile(found.map((note) => ({ note, ticks: 173 }))); setNotes(found); setMidiUrl(URL.createObjectURL(new Blob([bytes.buffer as ArrayBuffer], { type: "audio/midi" }))); setMessage(`${found.length} pitch changes detected from ${audio.duration.toFixed(1)} seconds of audio.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Audio analysis failed."); } finally { setBusy(false); } };
  return <ToolFrame title={name} status="experimental monophonic"><FilePicker accept="audio/mpeg,.mp3,audio/*" onFile={convert} busy={busy} hint="MP3 or browser-readable audio · clear single notes work best" />{message && <div className={midiUrl ? "notice-output" : "error-output"}>{message}</div>}{midiUrl && <div className="file-result"><ResultGrid values={[["Detected notes", String(notes.length)], ["MIDI range", `${Math.min(...notes)}–${Math.max(...notes)}`], ["Method", "Zero-crossing pitch trace"], ["Tempo grid", "120 BPM"]]} /><a className="plain-button primary-button" href={midiUrl} download="normal-tools-melody.mid">Download MIDI</a></div>}<p className="tool-caution">Experimental and meant for a clean, monophonic melody. Chords, drums, reverb, and full mixes will produce inaccurate notes.</p></ToolFrame>;
}

export function DwgTool({ name }: { name: string }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [svg, setSvg] = useState(""); const [filename, setFilename] = useState("");
  const convert = async (file: File) => { setBusy(true); setError(""); setSvg(""); try { const { LibreDwg, Dwg_File_Type } = await import("@mlightcad/libredwg-web"); const libredwg = await LibreDwg.create("/scripts/"); const pointer = libredwg.dwg_read_data(await file.arrayBuffer(), Dwg_File_Type.DWG); if (!pointer) throw new Error("The CAD parser could not open this DWG version."); const database = libredwg.convert(pointer); const result = libredwg.dwg_to_svg(database); libredwg.dwg_free(pointer); if (!result || !result.includes("<svg")) throw new Error("The drawing opened, but no printable model-space geometry was produced."); setSvg(result); setFilename(file.name); } catch (caught) { setError(caught instanceof Error ? caught.message : "DWG conversion failed."); } finally { setBusy(false); } };
  const print = () => { const popup = window.open("", "_blank"); if (!popup) { setError("Allow pop-ups for this page, then try again."); return; } popup.document.write(`<!doctype html><title>${filename}</title><style>body{margin:0;padding:20px}svg{width:100%;height:auto}@page{size:auto;margin:10mm}</style>${svg}<script>onload=()=>print()<\/script>`); popup.document.close(); };
  return <ToolFrame title={name} status="DWG → SVG → print"><FilePicker accept=".dwg,application/acad,application/x-acad" onFile={convert} busy={busy} hint="DWG drawing · model space parsed in WebAssembly" />{error && <div className="error-output">{error}</div>}{svg && <><div className="dwg-preview" dangerouslySetInnerHTML={{ __html: svg }} /><button className="plain-button primary-button" type="button" onClick={print}>Print / Save as PDF</button></>}<p className="tool-caution">Best for common 2D model-space entities. Fonts, xrefs, raster images, layouts, newer objects, and some proprietary entities may not render exactly like AutoCAD.</p></ToolFrame>;
}

type Point = [number, number, number];
function stlVertices(buffer: ArrayBuffer): Point[] { const text = new TextDecoder().decode(buffer.slice(0, Math.min(buffer.byteLength, 200))).trimStart(); if (text.startsWith("solid")) { const full = new TextDecoder().decode(buffer); return [...full.matchAll(/vertex\s+([-+\deE.]+)\s+([-+\deE.]+)\s+([-+\deE.]+)/g)].map((match) => [Number(match[1]), Number(match[2]), Number(match[3])]); } const view = new DataView(buffer); const count = view.getUint32(80, true); const points: Point[] = []; for (let triangle = 0; triangle < count && 84 + triangle * 50 + 50 <= buffer.byteLength; triangle++) { const base = 84 + triangle * 50 + 12; for (let vertex = 0; vertex < 3; vertex++) points.push([view.getFloat32(base + vertex * 12, true), view.getFloat32(base + vertex * 12 + 4, true), view.getFloat32(base + vertex * 12 + 8, true)]); } return points; }

export function StlTool({ name }: { name: string }) {
  const [busy, setBusy] = useState(false); const [layer, setLayer] = useState("0.2"); const [speed, setSpeed] = useState("1800"); const [gcode, setGcode] = useState(""); const [message, setMessage] = useState("");
  const convert = async (file: File) => { setBusy(true); setMessage(""); setGcode(""); try { const points = stlVertices(await file.arrayBuffer()); if (!points.length) throw new Error("No STL vertices were found."); let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity,minZ=Infinity,maxZ=-Infinity; for(const [x,y,z] of points){if(!Number.isFinite(x)||!Number.isFinite(y)||!Number.isFinite(z))continue;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);minZ=Math.min(minZ,z);maxZ=Math.max(maxZ,z);} if(!Number.isFinite(minX)||maxX<=minX||maxY<=minY)throw new Error("The STL does not contain a usable three-dimensional outline."); const height = Math.max(maxZ - minZ, Number(layer)); const layers = Math.min(2000, Math.ceil(height / Math.max(Number(layer), 0.05))); const lines = [`; Normal Tools draft outline G-code`, `; Source: ${file.name}`, `G21 ; millimeters`, `G90 ; absolute positioning`, `G28`, `G92 E0`, `M82`, `G1 F${Number(speed) || 1800}`]; let e = 0; const perimeter = 2 * ((maxX - minX) + (maxY - minY)); for (let index = 0; index < layers; index++) { const z = (index + 1) * Math.max(Number(layer), 0.05); e += perimeter * 0.045; lines.push(`; layer ${index + 1}`, `G0 X${minX.toFixed(3)} Y${minY.toFixed(3)} Z${z.toFixed(3)}`, `G1 X${maxX.toFixed(3)} Y${minY.toFixed(3)} E${(e * 0.25).toFixed(4)}`, `G1 X${maxX.toFixed(3)} Y${maxY.toFixed(3)} E${(e * 0.5).toFixed(4)}`, `G1 X${minX.toFixed(3)} Y${maxY.toFixed(3)} E${(e * 0.75).toFixed(4)}`, `G1 X${minX.toFixed(3)} Y${minY.toFixed(3)} E${e.toFixed(4)}`); } lines.push("M104 S0", "M140 S0", "M84"); setGcode(lines.join("\n")); setMessage(`${points.length / 3} triangles · ${layers} outline layers · ${(maxX - minX).toFixed(2)} × ${(maxY - minY).toFixed(2)} × ${height.toFixed(2)} mm`); } catch (error) { setMessage(error instanceof Error ? error.message : "STL conversion failed."); } finally { setBusy(false); } };
  return <ToolFrame title={name} status="draft outline mode"><div className="field-grid"><NumberField label="Layer height" value={layer} onChange={setLayer} min={0.05} step={0.05} suffix="mm" /><NumberField label="Print speed" value={speed} onChange={setSpeed} min={60} step={60} suffix="mm/min" /></div><FilePicker accept=".stl,model/stl" onFile={convert} busy={busy} hint="ASCII or binary STL · dimensions assumed to be millimeters" />{message && <div className={gcode ? "notice-output" : "error-output"}>{message}</div>}{gcode && <><textarea className="mono-input output-area" value={gcode} rows={14} readOnly /><ActionRow output={gcode} filename="outline.gcode" /></>}<p className="tool-caution">Safety limit: this creates rectangular outline preview G-code, not production slicing or infill. Inspect in a G-code viewer and use a real slicer before sending anything to a printer.</p></ToolFrame>;
}

export const fileSlugs = new Set(["bank-statement-pdf-to-csv-converter", "psd-to-png-converter", "mp3-to-midi-converter", "dwg-to-pdf-converter", "stl-to-g-code-converter"]);
