"use client";

import { useMemo, useState } from "react";
import { ActionRow, money, NumberField, number, ResultGrid, SelectField, ToolFrame } from "./shared";

type NumericField = { type?: "number"; key: string; label: string; initial: number; suffix?: string; min?: number; step?: number; help?: string };
type ChoiceField = { type: "select"; key: string; label: string; initial: string; options: Array<[string, string]> };
type Field = NumericField | ChoiceField;
type Values = Record<string, number | string>;
type Spec = { fields: Field[]; calculate: (values: Values) => Array<[string, string]>; note: string };

const n = (values: Values, key: string) => Number(values[key]) || 0;
const s = (values: Values, key: string) => String(values[key] ?? "");
const pct = (value: number) => `${number(value, 2)}%`;

const marketplaceFee = (marketplace: string, transactionRate: number, paymentRate: number, fixed = 0): Spec => ({
  fields: [
    { key: "sale", label: "Item sale price", initial: 100, suffix: "$", min: 0 },
    { key: "shipping", label: "Shipping charged", initial: 10, suffix: "$", min: 0 },
    { key: "cost", label: "Item cost", initial: 35, suffix: "$", min: 0 },
    { key: "shipCost", label: "Your shipping cost", initial: 10, suffix: "$", min: 0 },
    { key: "transaction", label: "Marketplace fee", initial: transactionRate, suffix: "%", min: 0, step: .01 },
    { key: "payment", label: "Payment fee", initial: paymentRate, suffix: "%", min: 0, step: .01 },
    { key: "fixed", label: "Fixed fee", initial: fixed, suffix: "$", min: 0, step: .01 },
    { key: "other", label: "Other seller costs", initial: 0, suffix: "$", min: 0 },
  ],
  calculate: (v) => { const gross=n(v,"sale")+n(v,"shipping"); const fees=gross*(n(v,"transaction")+n(v,"payment"))/100+n(v,"fixed")+n(v,"other"); const profit=gross-fees-n(v,"cost")-n(v,"shipCost"); return [["Buyer pays",money(gross)],["Estimated fees",money(fees)],["Seller payout",money(gross-fees)],["Net profit",money(profit)],["Profit margin",pct(profit/Math.max(gross,.01)*100)],["Break-even item price",money((n(v,"cost")+n(v,"shipCost")+n(v,"fixed")+n(v,"other"))/Math.max(1-(n(v,"transaction")+n(v,"payment"))/100,.01)-n(v,"shipping"))]]; },
  note: `Starts with a common ${marketplace} fee estimate. Rates vary by country, category, seller status, payment method, and promotions, so every assumption is editable.`,
});

const creatorProduct = (platform: string, payment = 2.9): Spec => ({
  fields: [{key:"price",label:"Sale price",initial:30,suffix:"$",min:0},{key:"base",label:"Base product cost",initial:14,suffix:"$",min:0},{key:"discount",label:"Discount",initial:0,suffix:"%",min:0},{key:"payment",label:"Payment fee",initial:payment,suffix:"%",min:0,step:.01},{key:"fixed",label:"Fixed fee",initial:.30,suffix:"$",min:0,step:.01},{key:"support",label:"Shipping / support cost",initial:0,suffix:"$",min:0},{key:"quantity",label:"Quantity",initial:25,min:1,step:1}],
  calculate:(v)=>{const charged=n(v,"price")*(1-n(v,"discount")/100);const fees=charged*n(v,"payment")/100+n(v,"fixed");const each=charged-n(v,"base")-fees-n(v,"support");return [["Customer price",money(charged)],["Fees per sale",money(fees)],["Profit per sale",money(each)],["Margin",pct(each/Math.max(charged,.01)*100)],["Projected profit",money(each*n(v,"quantity"))],["Break-even list price",money((n(v,"base")+n(v,"fixed")+n(v,"support"))/Math.max((1-n(v,"discount")/100)*(1-n(v,"payment")/100),.01))]];},
  note:`Use the exact ${platform} base cost and payment rate shown for the product, storefront, and buyer location. Taxes and returns are not included.`,
});

const specs: Record<string, Spec> = {
  "stockx-seller-fee-calculator": marketplaceFee("StockX",9,3),
  "grailed-fee-calculator": marketplaceFee("Grailed",9,3.49,.49),
  "reverb-fee-calculator": marketplaceFee("Reverb",5,3.19,.49),
  "discogs-fee-calculator": marketplaceFee("Discogs",9,0),
  "ko-fi-fee-calculator": marketplaceFee("Ko-fi",5,2.9,.30),
  "fiverr-fee-calculator": marketplaceFee("Fiverr",20,0),
  "upwork-fee-calculator": marketplaceFee("Upwork",10,0),
  "amazon-handmade-fee-calculator": marketplaceFee("Amazon Handmade",15,0),
  "kickstarter-fee-calculator": {
    fields:[{key:"pledged",label:"Successful pledges",initial:50000,suffix:"$",min:0},{key:"backers",label:"Backers",initial:600,min:1,step:1},{key:"failed",label:"Failed pledges",initial:4,suffix:"%",min:0},{key:"platform",label:"Platform fee",initial:5,suffix:"%",min:0},{key:"payment",label:"Payment fee",initial:3.2,suffix:"%",min:0},{key:"fixed",label:"Fixed fee per pledge",initial:.20,suffix:"$",min:0},{key:"rewards",label:"Rewards and fulfillment",initial:18000,suffix:"$",min:0}],
    calculate:(v)=>{const collected=n(v,"pledged")*(1-n(v,"failed")/100);const fees=collected*(n(v,"platform")+n(v,"payment"))/100+n(v,"backers")*n(v,"fixed");const net=collected-fees-n(v,"rewards");return [["Collected pledges",money(collected)],["Platform and payment fees",money(fees)],["After platform fees",money(collected-fees)],["After rewards / fulfillment",money(net)],["Net per backer",money(net/Math.max(n(v,"backers"),1))],["Effective retained rate",pct(net/Math.max(n(v,"pledged"),.01)*100)]];},
    note:"Use the campaign's actual payment mix and fulfillment budget. Taxes, refunds, currency conversion, and late production costs are not included.",
  },
  "youtube-rpm-calculator": {
    fields:[{key:"views",label:"Video views",initial:100000,min:0,step:1},{key:"rpm",label:"Estimated RPM",initial:4.5,suffix:"$",min:0,step:.01},{key:"actual",label:"Actual revenue",initial:450,suffix:"$",min:0},{key:"monthly",label:"Months at this volume",initial:12,min:1,step:1}],
    calculate:(v)=>{const estimate=n(v,"views")/1000*n(v,"rpm");const inferred=n(v,"actual")/Math.max(n(v,"views"),1)*1000;return [["Estimated revenue",money(estimate)],["Revenue per 1,000 views",money(n(v,"rpm"))],["RPM from actual revenue",money(inferred)],["Projected period revenue",money(estimate*n(v,"monthly"))],["Views for $1,000",number(1000/Math.max(n(v,"rpm"),.01)*1000,0)]];},
    note:"RPM is revenue after YouTube's share per 1,000 total views. It varies sharply by audience, topic, season, format, and monetized-playback rate.",
  },
  "twitch-subscription-revenue-calculator": {
    fields:[{key:"tier1",label:"Tier 1 subscribers",initial:250,min:0,step:1},{key:"tier2",label:"Tier 2 subscribers",initial:15,min:0,step:1},{key:"tier3",label:"Tier 3 subscribers",initial:5,min:0,step:1},{key:"split",label:"Creator revenue share",initial:50,suffix:"%",min:0},{key:"prime",label:"Prime subscribers",initial:80,min:0,step:1},{key:"primeValue",label:"Prime value before split",initial:4.99,suffix:"$",min:0}],
    calculate:(v)=>{const gross=n(v,"tier1")*4.99+n(v,"tier2")*9.99+n(v,"tier3")*24.99+n(v,"prime")*n(v,"primeValue");const net=gross*n(v,"split")/100;const subs=n(v,"tier1")+n(v,"tier2")+n(v,"tier3")+n(v,"prime");return [["Total subscribers",number(subs,0)],["Subscription gross",money(gross)],["Estimated creator revenue",money(net)],["Average per subscriber",money(net/Math.max(subs,1))],["Annualized revenue",money(net*12)]];},
    note:"Regional pricing, taxes, Prime terms, negotiated splits, Plus Program status, and payout adjustments can change actual revenue.",
  },
  "redbubble-profit-calculator": {
    fields:[{key:"base",label:"Base product price",initial:20,suffix:"$",min:0},{key:"margin",label:"Artist markup",initial:20,suffix:"%",min:0},{key:"account",label:"Account fee on earnings",initial:0,suffix:"%",min:0},{key:"discount",label:"Customer discount",initial:0,suffix:"%",min:0},{key:"quantity",label:"Quantity",initial:20,min:1,step:1}],
    calculate:(v)=>{const retail=n(v,"base")*(1+n(v,"margin")/100)*(1-n(v,"discount")/100);const artist=Math.max(0,retail-n(v,"base"));const net=artist*(1-n(v,"account")/100);return [["Retail price",money(retail)],["Artist margin",money(artist)],["Account fee",money(artist-net)],["Net per sale",money(net)],["Projected earnings",money(net*n(v,"quantity"))]];},
    note:"Base prices, discount allocation, account tiers, and product-specific markups vary. Enter the values shown in the product editor and account statement.",
  },
  "teespring-profit-calculator": creatorProduct("Spring",0),
  "fourthwall-profit-calculator": creatorProduct("Fourthwall",2.9),
  "shopify-break-even-roas-calculator": {
    fields:[{key:"price",label:"Average order value",initial:65,suffix:"$",min:0},{key:"cogs",label:"Product cost",initial:20,suffix:"$",min:0},{key:"shipping",label:"Shipping subsidy",initial:6,suffix:"$",min:0},{key:"payment",label:"Payment fee",initial:2.9,suffix:"%",min:0},{key:"fixed",label:"Fixed fee",initial:.30,suffix:"$",min:0},{key:"other",label:"Apps / handling per order",initial:3,suffix:"$",min:0},{key:"target",label:"Target net margin",initial:15,suffix:"%",min:0}],
    calculate:(v)=>{const nonAd=n(v,"cogs")+n(v,"shipping")+n(v,"other")+n(v,"price")*n(v,"payment")/100+n(v,"fixed");const contribution=n(v,"price")-nonAd;const targetProfit=n(v,"price")*n(v,"target")/100;const targetCpa=Math.max(0,contribution-targetProfit);return [["Non-ad costs",money(nonAd)],["Contribution before ads",money(contribution)],["Break-even CPA",money(contribution)],["Break-even ROAS",number(n(v,"price")/Math.max(contribution,.01),2)],["Target CPA",money(targetCpa)],["Target ROAS",number(n(v,"price")/Math.max(targetCpa,.01),2)]];},
    note:"Use blended order values and fully loaded variable costs. Refunds, chargebacks, taxes, and fixed overhead need separate allowances.",
  },
  "paver-calculator": {
    fields:[{key:"length",label:"Patio length",initial:20,suffix:"ft",min:0},{key:"width",label:"Patio width",initial:14,suffix:"ft",min:0},{key:"paverL",label:"Paver length",initial:8,suffix:"in",min:.1},{key:"paverW",label:"Paver width",initial:4,suffix:"in",min:.1},{key:"base",label:"Compacted base depth",initial:4,suffix:"in",min:0},{key:"sand",label:"Bedding sand depth",initial:1,suffix:"in",min:0},{key:"waste",label:"Paver waste",initial:10,suffix:"%",min:0}],
    calculate:(v)=>{const area=n(v,"length")*n(v,"width");const each=n(v,"paverL")*n(v,"paverW")/144;return [["Patio area",`${number(area,1)} sq ft`],["Pavers with waste",number(Math.ceil(area/Math.max(each,.001)*(1+n(v,"waste")/100)),0)],["Base material",`${number(area*n(v,"base")/324,2)} yd³`],["Bedding sand",`${number(area*n(v,"sand")/324,2)} yd³`],["Edge restraint",`${number(2*(n(v,"length")+n(v,"width")),1)} ft`]];},note:"Actual joint width, pattern, cuts, compaction, soil, drainage, and product dimensions affect the order."},
  "retaining-wall-block-calculator": {
    fields:[{key:"length",label:"Wall length",initial:40,suffix:"ft",min:0},{key:"height",label:"Wall height",initial:3,suffix:"ft",min:0},{key:"blockL",label:"Block face length",initial:16,suffix:"in",min:.1},{key:"blockH",label:"Block face height",initial:6,suffix:"in",min:.1},{key:"depth",label:"Drainage stone depth",initial:12,suffix:"in",min:0},{key:"waste",label:"Block waste",initial:8,suffix:"%",min:0}],
    calculate:(v)=>{const face=n(v,"length")*n(v,"height");const blockArea=n(v,"blockL")*n(v,"blockH")/144;const courses=Math.ceil(n(v,"height")*12/n(v,"blockH"));return [["Wall face",`${number(face,1)} sq ft`],["Courses",number(courses,0)],["Wall blocks",number(Math.ceil(face/Math.max(blockArea,.001)*(1+n(v,"waste")/100)),0)],["Cap blocks",number(Math.ceil(n(v,"length")*12/n(v,"blockL")),0)],["Drainage stone",`${number(n(v,"length")*n(v,"height")*n(v,"depth")/12/27,2)} yd³`]];},note:"Wall engineering, embedment, base thickness, drainage, surcharge, geogrid, frost, and permit requirements depend on the site and block system."},
  "topsoil-calculator": {
    fields:[{key:"length",label:"Area length",initial:40,suffix:"ft",min:0},{key:"width",label:"Area width",initial:20,suffix:"ft",min:0},{key:"depth",label:"Soil depth",initial:4,suffix:"in",min:0},{key:"density",label:"Bulk density",initial:1.1,suffix:"tons/yd³",min:0},{key:"bag",label:"Bag volume",initial:1.5,suffix:"cu ft",min:.1},{key:"waste",label:"Settlement allowance",initial:10,suffix:"%",min:0}],
    calculate:(v)=>{const ft3=n(v,"length")*n(v,"width")*n(v,"depth")/12*(1+n(v,"waste")/100);const yd=ft3/27;return [["Area",`${number(n(v,"length")*n(v,"width"),1)} sq ft`],["Cubic yards",number(yd,2)],["Estimated tons",number(yd*n(v,"density"),2)],["Bags",number(Math.ceil(ft3/Math.max(n(v,"bag"),.1)),0)]];},note:"Moisture, settling, soil blend, and supplier density change delivered volume and weight."},
  "pool-volume-calculator": {
    fields:[{type:"select",key:"shape",label:"Pool shape",initial:"rect",options:[["rect","Rectangle"],["oval","Oval / round-ended"]]},{key:"length",label:"Length",initial:30,suffix:"ft",min:0},{key:"width",label:"Width",initial:15,suffix:"ft",min:0},{key:"shallow",label:"Shallow depth",initial:3.5,suffix:"ft",min:0},{key:"deep",label:"Deep depth",initial:8,suffix:"ft",min:0},{key:"flow",label:"Fill rate",initial:12,suffix:"gal/min",min:.1}],
    calculate:(v)=>{const factor=s(v,"shape")==="oval"?.785398:1;const avg=(n(v,"shallow")+n(v,"deep"))/2;const gallons=n(v,"length")*n(v,"width")*avg*factor*7.48052;return [["Average depth",`${number(avg,2)} ft`],["Pool volume",`${number(gallons,0)} US gal`],["Liters",`${number(gallons*3.78541,0)} L`],["Water weight",`${number(gallons*8.345,0)} lb`],["Fill time",`${number(gallons/Math.max(n(v,"flow"),.1)/60,1)} hours`]];},note:"Use inside water dimensions. Steps, benches, slopes, curves, and the fill line reduce actual volume."},
  "pond-liner-calculator": {
    fields:[{key:"length",label:"Maximum pond length",initial:14,suffix:"ft",min:0},{key:"width",label:"Maximum pond width",initial:10,suffix:"ft",min:0},{key:"depth",label:"Maximum depth",initial:3,suffix:"ft",min:0},{key:"overlap",label:"Edge overlap each side",initial:1.5,suffix:"ft",min:0}],
    calculate:(v)=>{const linerL=n(v,"length")+2*n(v,"depth")+2*n(v,"overlap");const linerW=n(v,"width")+2*n(v,"depth")+2*n(v,"overlap");const gal=n(v,"length")*n(v,"width")*n(v,"depth")*.7*7.48052;return [["Liner length",`${number(linerL,1)} ft`],["Liner width",`${number(linerW,1)} ft`],["Liner area",`${number(linerL*linerW,1)} sq ft`],["Approximate pond volume",`${number(gal,0)} gal`],["Underlayment area",`${number(linerL*linerW*1.1,1)} sq ft`]];},note:"The volume uses a shape allowance for sloped sides. Add more liner for shelves, waterfalls, irregular edges, and anchoring details."},
  "french-drain-gravel-calculator": {
    fields:[{key:"length",label:"Drain length",initial:80,suffix:"ft",min:0},{key:"width",label:"Trench width",initial:12,suffix:"in",min:0},{key:"depth",label:"Gravel depth",initial:18,suffix:"in",min:0},{key:"pipe",label:"Pipe outside diameter",initial:4,suffix:"in",min:0},{key:"waste",label:"Compaction / waste",initial:10,suffix:"%",min:0}],
    calculate:(v)=>{const trench=n(v,"length")*n(v,"width")/12*n(v,"depth")/12;const pipe=Math.PI*(n(v,"pipe")/24)**2*n(v,"length");const gravel=Math.max(0,trench-pipe)*(1+n(v,"waste")/100);const fabric=n(v,"length")*(2*n(v,"depth")/12+n(v,"width")/12)*1.1;return [["Trench volume",`${number(trench/27,2)} yd³`],["Gravel to order",`${number(gravel/27,2)} yd³`],["Approximate tons",`${number(gravel/27*1.4,2)} tons`],["Pipe length",`${number(n(v,"length")*1.05,1)} ft`],["Filter fabric",`${number(fabric,1)} sq ft`]];},note:"Soil, stone size, trench profile, outlet, slope, fabric overlap, and local drainage rules affect the installation."},
  "asphalt-driveway-calculator": {
    fields:[{key:"length",label:"Driveway length",initial:60,suffix:"ft",min:0},{key:"width",label:"Driveway width",initial:12,suffix:"ft",min:0},{key:"depth",label:"Compacted thickness",initial:3,suffix:"in",min:0},{key:"density",label:"Asphalt density",initial:2.025,suffix:"tons/yd³",min:0},{key:"waste",label:"Waste",initial:5,suffix:"%",min:0},{key:"price",label:"Price per ton",initial:130,suffix:"$",min:0},{key:"truck",label:"Truck capacity",initial:20,suffix:"tons",min:.1}],
    calculate:(v)=>{const yd=n(v,"length")*n(v,"width")*n(v,"depth")/324*(1+n(v,"waste")/100);const tons=yd*n(v,"density");return [["Surface area",`${number(n(v,"length")*n(v,"width"),1)} sq ft`],["Compacted volume",`${number(yd,2)} yd³`],["Asphalt",`${number(tons,2)} tons`],["Truckloads",number(Math.ceil(tons/Math.max(n(v,"truck"),.1)),0)],["Material cost",money(tons*n(v,"price"))]];},note:"Mix density, lift thickness, compaction, subbase, mobilization, minimum loads, and local pricing can change the quote."},
  "roofing-shingle-bundle-calculator": {
    fields:[{key:"area",label:"Total roof surface area",initial:2400,suffix:"sq ft",min:0},{key:"waste",label:"Waste and cuts",initial:12,suffix:"%",min:0},{key:"bundles",label:"Bundles per square",initial:3,min:1},{key:"under",label:"Underlayment roll coverage",initial:400,suffix:"sq ft",min:1},{key:"ridge",label:"Ridge / hip length",initial:70,suffix:"ft",min:0},{key:"ridgeCoverage",label:"Ridge coverage per bundle",initial:33,suffix:"ft",min:1}],
    calculate:(v)=>{const adjusted=n(v,"area")*(1+n(v,"waste")/100);const squares=adjusted/100;return [["Roof squares",number(squares,2)],["Shingle bundles",number(Math.ceil(squares*n(v,"bundles")),0)],["Underlayment rolls",number(Math.ceil(adjusted/n(v,"under")),0)],["Ridge-cap bundles",number(Math.ceil(n(v,"ridge")/n(v,"ridgeCoverage")),0)],["Roofing nails",`${number(Math.ceil(squares*320),0)} approx.`]];},note:"Valleys, starter strips, flashing, ventilation, ice barrier, steep-slope rules, and manufacturer instructions require separate quantities."},
  "stud-wall-calculator": {
    fields:[{key:"length",label:"Wall length",initial:24,suffix:"ft",min:0},{key:"height",label:"Wall height",initial:8,suffix:"ft",min:0},{key:"spacing",label:"Stud spacing",initial:16,suffix:"in",min:1},{key:"openings",label:"Doors and windows",initial:2,min:0,step:1},{key:"plates",label:"Plate runs",initial:3,min:1,step:1},{key:"waste",label:"Lumber waste",initial:10,suffix:"%",min:0}],
    calculate:(v)=>{const base=Math.ceil(n(v,"length")*12/n(v,"spacing"))+1;const studs=Math.ceil((base+n(v,"openings")*4)*(1+n(v,"waste")/100));const plates=n(v,"length")*n(v,"plates")*(1+n(v,"waste")/100);return [["Field studs",number(base,0)],["Studs with openings / waste",number(studs,0)],["Plate lumber",`${number(plates,1)} linear ft`],["Wall face",`${number(n(v,"length")*n(v,"height"),1)} sq ft`],["8 ft plate boards",number(Math.ceil(plates/8),0)]];},note:"Corners, intersecting walls, headers, king and jack studs, blocking, structural loads, and local code change the framing takeoff."},
  "insulation-calculator": {
    fields:[{key:"length",label:"Surface length",initial:40,suffix:"ft",min:0},{key:"height",label:"Surface height",initial:8,suffix:"ft",min:0},{key:"openings",label:"Openings",initial:35,suffix:"sq ft",min:0},{key:"pack",label:"Coverage per pack",initial:106.7,suffix:"sq ft",min:1},{key:"waste",label:"Waste",initial:10,suffix:"%",min:0},{key:"cost",label:"Cost per pack",initial:75,suffix:"$",min:0}],
    calculate:(v)=>{const area=Math.max(0,n(v,"length")*n(v,"height")-n(v,"openings"));const order=area*(1+n(v,"waste")/100);const packs=Math.ceil(order/n(v,"pack"));return [["Net area",`${number(area,1)} sq ft`],["Area with waste",`${number(order,1)} sq ft`],["Packs needed",number(packs,0)],["Estimated material cost",money(packs*n(v,"cost"))]];},note:"Match cavity depth, framing spacing, R-value, vapor control, fire rules, and product coverage to the exact assembly."},
  "hvac-btu-calculator": {
    fields:[{key:"area",label:"Room area",initial:500,suffix:"sq ft",min:0},{key:"ceiling",label:"Ceiling height",initial:8,suffix:"ft",min:1},{key:"climate",label:"Climate / exposure factor",initial:1,suffix:"×",min:.5,step:.05},{key:"windows",label:"Sunny windows",initial:3,min:0,step:1},{key:"people",label:"Regular occupants",initial:2,min:0,step:1}],
    calculate:(v)=>{const btu=n(v,"area")*20*(n(v,"ceiling")/8)*n(v,"climate")+n(v,"windows")*1000+Math.max(0,n(v,"people")-2)*600;return [["Estimated capacity",`${number(btu,0)} BTU/hr`],["Nominal tons",number(btu/12000,2)],["Rounded common size",`${number(Math.ceil(btu/6000)*6000,0)} BTU/hr`],["Airflow rule of thumb",`${number(btu/12000*400,0)} CFM`]];},note:"This is a quick sizing estimate, not a Manual J load calculation. Insulation, leakage, orientation, humidity, ducts, climate, and equipment performance matter."},
  "ac-tonnage-calculator": {
    fields:[{key:"area",label:"Conditioned area",initial:1800,suffix:"sq ft",min:0},{key:"load",label:"Design load",initial:24,suffix:"BTU/sq ft",min:1},{key:"ceiling",label:"Ceiling adjustment",initial:1,suffix:"×",min:.5,step:.05},{key:"duct",label:"Duct / leakage allowance",initial:10,suffix:"%",min:0}],
    calculate:(v)=>{const btu=n(v,"area")*n(v,"load")*n(v,"ceiling")*(1+n(v,"duct")/100);const tons=btu/12000;return [["Estimated load",`${number(btu,0)} BTU/hr`],["Calculated tonnage",number(tons,2)],["Nearest half ton",number(Math.ceil(tons*2)/2,1)],["Suggested airflow",`${number(tons*400,0)} CFM`]];},note:"Oversizing can reduce comfort and humidity control. Confirm equipment with a licensed professional and a room-by-room load calculation."},
  "pipe-volume-calculator": {
    fields:[{key:"diameter",label:"Inside diameter",initial:2,suffix:"in",min:0},{key:"length",label:"Pipe length",initial:100,suffix:"ft",min:0},{key:"density",label:"Fluid weight",initial:8.345,suffix:"lb/gal",min:0},{key:"flow",label:"Flow rate",initial:10,suffix:"gal/min",min:.1}],
    calculate:(v)=>{const ft3=Math.PI*(n(v,"diameter")/24)**2*n(v,"length");const gal=ft3*7.48052;return [["Internal volume",`${number(ft3,3)} cu ft`],["US gallons",number(gal,3)],["Liters",number(gal*3.78541,2)],["Fluid weight",`${number(gal*n(v,"density"),2)} lb`],["Flush / fill time",`${number(gal/n(v,"flow"),2)} min`]];},note:"Use actual inside diameter, not nominal pipe size. Fittings, valves, slope, and incomplete fill change the result."},
  "gutter-size-calculator": {
    fields:[{key:"area",label:"Roof drainage area",initial:1800,suffix:"sq ft",min:0},{key:"pitch",label:"Pitch area factor",initial:1.1,suffix:"×",min:1},{key:"rain",label:"Rainfall intensity",initial:4,suffix:"in/hr",min:.1},{key:"downspout",label:"Capacity per downspout",initial:600,suffix:"sq ft",min:1}],
    calculate:(v)=>{const adjusted=n(v,"area")*n(v,"pitch");const flow=adjusted*n(v,"rain")/96.23;const size=adjusted<=2500?"5-inch K-style":adjusted<=3800?"6-inch K-style":"7-inch or engineered";return [["Adjusted roof area",`${number(adjusted,0)} sq ft`],["Peak runoff",`${number(flow,1)} gal/min`],["Starting gutter size",size],["Downspouts",number(Math.ceil(adjusted/n(v,"downspout")),0)],["Area per downspout",`${number(adjusted/Math.max(Math.ceil(adjusted/n(v,"downspout")),1),0)} sq ft`]];},note:"Valleys, roof geometry, outlet location, local design rainfall, gutter profile, slope, and debris can require larger components."},
  "ramp-slope-calculator": {
    fields:[{key:"rise",label:"Vertical rise",initial:30,suffix:"in",min:0},{key:"ratio",label:"Run per 1 inch rise",initial:12,suffix:"in",min:1},{key:"maxRun",label:"Maximum run per section",initial:30,suffix:"ft",min:1},{key:"landing",label:"Landing length",initial:5,suffix:"ft",min:0}],
    calculate:(v)=>{const run=n(v,"rise")*n(v,"ratio")/12;const sections=Math.max(1,Math.ceil(run/n(v,"maxRun")));const landings=Math.max(0,sections-1);return [["Required sloped run",`${number(run,2)} ft`],["Slope",`1:${number(n(v,"ratio"),2)}`],["Grade",pct(100/n(v,"ratio"))],["Angle",`${number(Math.atan(1/n(v,"ratio"))*180/Math.PI,2)}°`],["Ramp sections",number(sections,0)],["Total length with landings",`${number(run+landings*n(v,"landing"),2)} ft`]];},note:"Accessibility and building rules also govern maximum rise, landings, handrails, edge protection, width, surface, and clearances. Verify local code."},
  "wire-size-calculator": {
    fields:[{key:"amps",label:"Load current",initial:20,suffix:"A",min:0},{key:"length",label:"One-way run",initial:75,suffix:"ft",min:0},{key:"voltage",label:"System voltage",initial:120,suffix:"V",min:1},{key:"drop",label:"Maximum voltage drop",initial:3,suffix:"%",min:.1}],
    calculate:(v)=>{const gauges=[{g:14,a:15,r:2.525},{g:12,a:20,r:1.588},{g:10,a:30,r:.999},{g:8,a:40,r:.6282},{g:6,a:55,r:.3951},{g:4,a:70,r:.2485},{g:3,a:85,r:.197},{g:2,a:95,r:.1563},{g:1,a:110,r:.1239},{g:0,a:125,r:.0983}];const suitable=gauges.find(x=>x.a>=n(v,"amps")&&2*n(v,"length")*x.r/1000*n(v,"amps")/n(v,"voltage")*100<=n(v,"drop"))||gauges[gauges.length-1];const volts=2*n(v,"length")*suitable.r/1000*n(v,"amps");return [["Starting copper size",`${suitable.g===0?"1/0":suitable.g} AWG`],["Table ampacity",`${suitable.a} A`],["Estimated drop",`${number(volts,2)} V`],["Drop percentage",pct(volts/n(v,"voltage")*100)],["Load voltage",`${number(n(v,"voltage")-volts,2)} V`]];},note:"This simplified copper table is not an electrical design. Temperature, terminals, insulation, bundling, conduit fill, continuous loads, motor startup, code, and aluminum conductors change sizing."},
  "voltage-drop-calculator": {
    fields:[{key:"amps",label:"Current",initial:20,suffix:"A",min:0},{key:"length",label:"One-way length",initial:75,suffix:"ft",min:0},{key:"voltage",label:"Source voltage",initial:120,suffix:"V",min:1},{type:"select",key:"gauge",label:"Copper wire size",initial:"12",options:[["14","14 AWG"],["12","12 AWG"],["10","10 AWG"],["8","8 AWG"],["6","6 AWG"],["4","4 AWG"],["2","2 AWG"],["0","1/0 AWG"]]},{type:"select",key:"phase",label:"Circuit",initial:"single",options:[["single","Single phase / DC"],["three","Three phase"]]}],
    calculate:(v)=>{const resistance:Record<string,number>={"14":2.525,"12":1.588,"10":.999,"8":.6282,"6":.3951,"4":.2485,"2":.1563,"0":.0983};const multiplier=s(v,"phase")==="three"?Math.sqrt(3):2;const drop=multiplier*n(v,"length")*(resistance[s(v,"gauge")]||1.588)/1000*n(v,"amps");return [["Voltage drop",`${number(drop,3)} V`],["Drop percentage",pct(drop/n(v,"voltage")*100)],["Voltage at load",`${number(n(v,"voltage")-drop,3)} V`],["Wire power loss",`${number(drop*n(v,"amps"),2)} W`],["Loop resistance",`${number(drop/Math.max(n(v,"amps"),.001),4)} Ω`]];},note:"Uses approximate copper resistance at room temperature. Verify conductor ampacity, operating temperature, circuit topology, code, and equipment requirements."},
  "ohms-law-calculator": {
    fields:[{type:"select",key:"mode",label:"Known values",initial:"vi",options:[["vi","Voltage and current"],["vr","Voltage and resistance"],["ir","Current and resistance"]]},{key:"voltage",label:"Voltage",initial:12,suffix:"V",min:0},{key:"current",label:"Current",initial:2,suffix:"A",min:0},{key:"resistance",label:"Resistance",initial:6,suffix:"Ω",min:0}],
    calculate:(v)=>{let volts=n(v,"voltage"),amps=n(v,"current"),ohms=n(v,"resistance");if(s(v,"mode")==="vi")ohms=volts/Math.max(amps,.000001);if(s(v,"mode")==="vr")amps=volts/Math.max(ohms,.000001);if(s(v,"mode")==="ir")volts=amps*ohms;return [["Voltage",`${number(volts,6)} V`],["Current",`${number(amps,6)} A`],["Resistance",`${number(ohms,6)} Ω`],["Power",`${number(volts*amps,6)} W`],["Energy in one hour",`${number(volts*amps,4)} Wh`]];},note:"Choose which two values are known. The unused input is ignored. Real components may be nonlinear and change resistance with temperature."},
  "led-resistor-calculator": {
    fields:[{key:"supply",label:"Supply voltage",initial:12,suffix:"V",min:0},{key:"forward",label:"LED forward voltage",initial:2.2,suffix:"V",min:0},{key:"count",label:"LEDs in series",initial:3,min:1,step:1},{key:"current",label:"Target LED current",initial:20,suffix:"mA",min:.1}],
    calculate:(v)=>{const ledVolts=n(v,"forward")*n(v,"count");const head=Math.max(0,n(v,"supply")-ledVolts);const resistance=head/(n(v,"current")/1000);const standards=[10,12,15,18,22,27,33,39,47,56,68,82];const decade=10**Math.floor(Math.log10(Math.max(resistance,1)));const standard=standards.map(x=>x*decade/10).find(x=>x>=resistance)||10*decade;const power=head*(n(v,"current")/1000);return [["LED string voltage",`${number(ledVolts,2)} V`],["Voltage across resistor",`${number(head,2)} V`],["Calculated resistance",`${number(resistance,1)} Ω`],["Next E12 value",`${number(standard,0)} Ω`],["Resistor dissipation",`${number(power,3)} W`],["Suggested resistor rating",`${number(Math.max(.125,Math.ceil(power*2*8)/8),3)} W`]];},note:"Confirm the LED datasheet, maximum current, forward-voltage range, resistor tolerance, temperature, and supply variation. High-power LEDs need regulated drivers."},
  "speaker-box-volume-calculator": {
    fields:[{key:"width",label:"Outside width",initial:24,suffix:"in",min:0},{key:"height",label:"Outside height",initial:16,suffix:"in",min:0},{key:"depth",label:"Outside depth",initial:15,suffix:"in",min:0},{key:"panel",label:"Panel thickness",initial:.75,suffix:"in",min:0},{key:"driver",label:"Driver displacement",initial:2.5,suffix:"L",min:0},{key:"port",label:"Port displacement",initial:1.2,suffix:"L",min:0},{key:"bracing",label:"Bracing displacement",initial:1,suffix:"L",min:0}],
    calculate:(v)=>{const iw=Math.max(0,n(v,"width")-2*n(v,"panel"));const ih=Math.max(0,n(v,"height")-2*n(v,"panel"));const id=Math.max(0,n(v,"depth")-2*n(v,"panel"));const gross=iw*ih*id*.0163871;const net=Math.max(0,gross-n(v,"driver")-n(v,"port")-n(v,"bracing"));return [["Internal dimensions",`${number(iw,2)} × ${number(ih,2)} × ${number(id,2)} in`],["Gross internal volume",`${number(gross,2)} L`],["Total displacement",`${number(n(v,"driver")+n(v,"port")+n(v,"bracing"),2)} L`],["Net enclosure volume",`${number(net,2)} L`],["Net cubic feet",number(net/28.3168,3)]];},note:"Internal dividers, lining, irregular panels, slot ports, and manufacturer enclosure targets need separate modeling."},
  "projector-throw-distance-calculator": {
    fields:[{key:"diagonal",label:"Screen diagonal",initial:120,suffix:"in",min:1},{type:"select",key:"aspect",label:"Aspect ratio",initial:"16:9",options:[["16:9","16:9"],["16:10","16:10"],["4:3","4:3"]]},{key:"min",label:"Minimum throw ratio",initial:1.13,suffix:"×",min:.01,step:.01},{key:"max",label:"Maximum throw ratio",initial:1.47,suffix:"×",min:.01,step:.01}],
    calculate:(v)=>{const [a,b]=s(v,"aspect").split(":").map(Number);const width=n(v,"diagonal")*a/Math.hypot(a,b);const height=n(v,"diagonal")*b/Math.hypot(a,b);return [["Image width",`${number(width,2)} in`],["Image height",`${number(height,2)} in`],["Minimum lens distance",`${number(width*n(v,"min")/12,2)} ft`],["Maximum lens distance",`${number(width*n(v,"max")/12,2)} ft`],["Screen area",`${number(width*height/144,1)} sq ft`]];},note:"Throw ratio normally uses image width. Lens shift, zoom range, mounting offset, overscan, and the manufacturer's calculator determine final placement."},
  "ups-runtime-calculator": {
    fields:[{key:"voltage",label:"Battery voltage",initial:12,suffix:"V",min:0},{key:"ah",label:"Battery capacity",initial:9,suffix:"Ah",min:0},{key:"batteries",label:"Battery count",initial:2,min:1,step:1},{key:"load",label:"Connected load",initial:180,suffix:"W",min:.1},{key:"eff",label:"Inverter efficiency",initial:85,suffix:"%",min:1},{key:"usable",label:"Usable capacity",initial:65,suffix:"%",min:1}],
    calculate:(v)=>{const stored=n(v,"voltage")*n(v,"ah")*n(v,"batteries");const usable=stored*n(v,"eff")/100*n(v,"usable")/100;const hours=usable/n(v,"load");return [["Nominal battery energy",`${number(stored,1)} Wh`],["Usable AC energy",`${number(usable,1)} Wh`],["Estimated runtime",`${number(hours*60,1)} minutes`],["Estimated runtime",`${number(hours,2)} hours`],["Load at battery",`${number(n(v,"load")/(n(v,"eff")/100),1)} W`]];},note:"Real UPS runtime is nonlinear and depends on battery age, discharge rate, temperature, inverter overhead, topology, and manufacturer cutoffs."},
  "propane-usage-calculator": {
    fields:[{key:"btu",label:"Appliance input",initial:60000,suffix:"BTU/hr",min:0},{key:"hours",label:"Hours used per day",initial:4,suffix:"hr",min:0},{key:"tank",label:"Usable propane in tank",initial:20,suffix:"lb",min:.1},{key:"days",label:"Planning period",initial:30,suffix:"days",min:1},{key:"price",label:"Price per gallon",initial:2.75,suffix:"$",min:0}],
    calculate:(v)=>{const galDay=n(v,"btu")*n(v,"hours")/91502;const tankGal=n(v,"tank")/4.24;return [["Propane per day",`${number(galDay,3)} gal`],["Propane per day",`${number(galDay*4.24,2)} lb`],["Tank runtime",`${number(tankGal/Math.max(galDay,.0001),1)} days`],["Period usage",`${number(galDay*n(v,"days"),2)} gal`],["Period fuel cost",money(galDay*n(v,"days")*n(v,"price"))]];},note:"Uses about 91,502 BTU per gallon. Actual firing rate, cycling, temperature, tank fill limit, altitude, and appliance efficiency change consumption."},
  "fuel-trip-cost-calculator": {
    fields:[{key:"distance",label:"Trip distance",initial:850,suffix:"mi",min:0},{key:"mpg",label:"Vehicle fuel economy",initial:28,suffix:"mpg",min:.1},{key:"price",label:"Fuel price",initial:3.45,suffix:"$/gal",min:0},{key:"travelers",label:"Travelers splitting cost",initial:2,min:1,step:1},{key:"tank",label:"Usable tank capacity",initial:13,suffix:"gal",min:.1},{key:"buffer",label:"Traffic / detour allowance",initial:5,suffix:"%",min:0}],
    calculate:(v)=>{const miles=n(v,"distance")*(1+n(v,"buffer")/100);const gallons=miles/n(v,"mpg");const cost=gallons*n(v,"price");return [["Adjusted distance",`${number(miles,1)} mi`],["Fuel needed",`${number(gallons,2)} gal`],["Estimated fuel cost",money(cost)],["Cost per traveler",money(cost/n(v,"travelers"))],["Fuel stops",number(Math.max(0,Math.ceil(gallons/n(v,"tank"))-1),0)],["Fuel cost per mile",money(cost/Math.max(miles,.01))]];},note:"Traffic, weather, terrain, speed, idling, tolls, vehicle load, and regional fuel prices can change actual trip cost."},
  "solar-battery-bank-calculator": {
    fields:[{key:"daily",label:"Daily energy use",initial:3000,suffix:"Wh",min:0},{key:"days",label:"Days of autonomy",initial:2,suffix:"days",min:.1},{key:"voltage",label:"Battery-bank voltage",initial:48,suffix:"V",min:1},{key:"dod",label:"Usable depth of discharge",initial:80,suffix:"%",min:1},{key:"eff",label:"System efficiency",initial:90,suffix:"%",min:1},{key:"module",label:"Battery module capacity",initial:100,suffix:"Ah",min:.1}],
    calculate:(v)=>{const usable=n(v,"daily")*n(v,"days");const nominal=usable/(n(v,"dod")/100)/(n(v,"eff")/100);const ah=nominal/n(v,"voltage");return [["Required usable energy",`${number(usable,0)} Wh`],["Nominal bank energy",`${number(nominal,0)} Wh`],["Required capacity",`${number(ah,1)} Ah at ${number(n(v,"voltage"),0)} V`],["Battery modules",number(Math.ceil(ah/n(v,"module")),0)],["Nominal kWh",`${number(nominal/1000,2)} kWh`]];},note:"Battery chemistry, surge loads, inverter limits, temperature, aging, series/parallel layout, reserve policy, and code require a complete system design."},
  "sourdough-calculator": {
    fields:[{key:"flour",label:"Total flour",initial:500,suffix:"g",min:0},{key:"hydration",label:"Target hydration",initial:72,suffix:"%",min:0},{key:"starter",label:"Starter amount",initial:20,suffix:"% flour",min:0},{key:"starterHydration",label:"Starter hydration",initial:100,suffix:"%",min:0},{key:"salt",label:"Salt",initial:2,suffix:"% flour",min:0}],
    calculate:(v)=>{const starterTotal=n(v,"flour")*n(v,"starter")/100;const starterFlour=starterTotal/(1+n(v,"starterHydration")/100);const starterWater=starterTotal-starterFlour;const addedFlour=Math.max(0,n(v,"flour")-starterFlour);const totalWater=n(v,"flour")*n(v,"hydration")/100;const addedWater=Math.max(0,totalWater-starterWater);const salt=n(v,"flour")*n(v,"salt")/100;return [["Flour to add",`${number(addedFlour,1)} g`],["Water to add",`${number(addedWater,1)} g`],["Starter",`${number(starterTotal,1)} g`],["Salt",`${number(salt,1)} g`],["Final dough weight",`${number(n(v,"flour")+totalWater+salt,1)} g`],["Prefermented flour",pct(starterFlour/Math.max(n(v,"flour"),1)*100)]];},note:"Total flour includes flour inside the starter. Flour absorption, temperature, fermentation schedule, and handling may call for hydration adjustments."},
  "meat-cooking-time-calculator": {
    fields:[{type:"select",key:"meat",label:"Meat",initial:"beef",options:[["beef","Beef roast"],["pork","Pork roast"],["chicken","Whole chicken"],["lamb","Lamb roast"]]},{key:"weight",label:"Weight",initial:5,suffix:"lb",min:.1},{key:"minutes",label:"Minutes per pound",initial:22,suffix:"min/lb",min:1},{key:"preheat",label:"Preheat / setup",initial:20,suffix:"min",min:0},{key:"rest",label:"Resting time",initial:20,suffix:"min",min:0}],
    calculate:(v)=>{const cook=n(v,"weight")*n(v,"minutes");return [["Selected meat",s(v,"meat")],["Estimated cook time",`${number(cook,0)} minutes`],["Cook time",`${Math.floor(cook/60)} hr ${Math.round(cook%60)} min`],["Total kitchen window",`${number(cook+n(v,"preheat")+n(v,"rest"),0)} minutes`],["Resting time",`${number(n(v,"rest"),0)} minutes`]];},note:"Time is only planning guidance. Use a calibrated food thermometer and current food-safety guidance for the exact cut, method, and target temperature."},
  "cake-pan-size-converter": {
    fields:[{type:"select",key:"sourceShape",label:"Original pan shape",initial:"round",options:[["round","Round"],["square","Square / rectangle"]]},{key:"sourceA",label:"Original diameter / length",initial:9,suffix:"in",min:.1},{key:"sourceB",label:"Original width",initial:9,suffix:"in",min:.1},{type:"select",key:"targetShape",label:"New pan shape",initial:"round",options:[["round","Round"],["square","Square / rectangle"]]},{key:"targetA",label:"New diameter / length",initial:8,suffix:"in",min:.1},{key:"targetB",label:"New width",initial:8,suffix:"in",min:.1},{key:"originalBatter",label:"Original batter amount",initial:6,suffix:"cups",min:0}],
    calculate:(v)=>{const area=(shape:string,a:number,b:number)=>shape==="round"?Math.PI*(a/2)**2:a*b;const source=area(s(v,"sourceShape"),n(v,"sourceA"),n(v,"sourceB"));const target=area(s(v,"targetShape"),n(v,"targetA"),n(v,"targetB"));const factor=target/source;return [["Original pan area",`${number(source,2)} sq in`],["New pan area",`${number(target,2)} sq in`],["Recipe scale",`${number(factor,3)}×`],["Percent of original",pct(factor*100)],["Batter for new pan",`${number(n(v,"originalBatter")*factor,2)} cups`]];},note:"This compares pan area, assuming similar depth. Fill level, shape, recipe chemistry, and bake time still need adjustment."},
  "yeast-converter": {
    fields:[{key:"amount",label:"Amount",initial:7,suffix:"g",min:0},{type:"select",key:"source",label:"Yeast type",initial:"instant",options:[["instant","Instant yeast"],["active","Active dry yeast"],["fresh","Fresh / cake yeast"]]}],
    calculate:(v)=>{const gramsInstant=n(v,"amount")*({instant:1,active:.8,fresh:.333}[s(v,"source")]||1);const active=gramsInstant/0.8;const fresh=gramsInstant/.333;return [["Instant yeast",`${number(gramsInstant,2)} g`],["Active dry yeast",`${number(active,2)} g`],["Fresh yeast",`${number(fresh,2)} g`],["Instant teaspoons",number(gramsInstant/3.1,2)],["Active dry teaspoons",number(active/3.1,2)],["Instant ounces",number(gramsInstant/28.3495,3)]];},note:"Conversion ratios vary by brand and recipe. The amount field is interpreted as grams of the selected yeast type."},
  "rice-water-ratio-calculator": {
    fields:[{type:"select",key:"rice",label:"Rice type",initial:"white",options:[["white","Long-grain white"],["jasmine","Jasmine"],["basmati","Basmati"],["brown","Brown rice"],["sushi","Sushi rice"]]},{key:"riceCups",label:"Dry rice",initial:2,suffix:"cups",min:0},{key:"serving",label:"Cooked rice per serving",initial:.75,suffix:"cups",min:.1}],
    calculate:(v)=>{const map:Record<string,{ratio:number,yield:number,time:number}>={white:{ratio:1.5,yield:3,time:18},jasmine:{ratio:1.25,yield:3,time:15},basmati:{ratio:1.5,yield:3,time:17},brown:{ratio:2,yield:3,time:42},sushi:{ratio:1.2,yield:2.8,time:20}};const item=map[s(v,"rice")]||map.white;const cooked=n(v,"riceCups")*item.yield;return [["Water",`${number(n(v,"riceCups")*item.ratio,2)} cups`],["Expected cooked rice",`${number(cooked,2)} cups`],["Approximate servings",number(cooked/n(v,"serving"),1)],["Covered simmer time",`${item.time} minutes`],["Water ratio",`1 : ${item.ratio}`]];},note:"These are stovetop starting ratios. Rice age, rinsing, soaking, pot seal, altitude, and brand can change water and cooking time."},
  "cocktail-dilution-calculator": {
    fields:[{key:"spirit",label:"Spirit volume",initial:2,suffix:"oz",min:0},{key:"spiritAbv",label:"Spirit ABV",initial:40,suffix:"%",min:0},{key:"other",label:"Other liquid volume",initial:1,suffix:"oz",min:0},{key:"otherAbv",label:"Other liquid ABV",initial:0,suffix:"%",min:0},{key:"dilution",label:"Water dilution",initial:25,suffix:"% pre-dilution",min:0}],
    calculate:(v)=>{const before=n(v,"spirit")+n(v,"other");const alcohol=n(v,"spirit")*n(v,"spiritAbv")/100+n(v,"other")*n(v,"otherAbv")/100;const water=before*n(v,"dilution")/100;const final=before+water;return [["Pre-dilution volume",`${number(before,2)} oz`],["Added water",`${number(water,2)} oz`],["Final drink volume",`${number(final,2)} oz`],["Final ABV",pct(alcohol/Math.max(final,.01)*100)],["Pure alcohol",`${number(alcohol,3)} oz`]];},note:"Ice temperature, size, time, technique, and glassware cause real dilution to vary. Alcohol affects people differently; serve responsibly."},
  "tip-calculator": {
    fields:[{key:"bill",label:"Bill before tip",initial:86.40,suffix:"$",min:0},{key:"tip",label:"Tip",initial:20,suffix:"%",min:0},{key:"people",label:"People",initial:3,min:1,step:1},{key:"tax",label:"Tax already in bill",initial:7.20,suffix:"$",min:0}],
    calculate:(v)=>{const pretax=Math.max(0,n(v,"bill")-n(v,"tax"));const tip=pretax*n(v,"tip")/100;const total=n(v,"bill")+tip;return [["Pre-tax amount",money(pretax)],["Tip amount",money(tip)],["Total",money(total)],["Per person",money(total/n(v,"people"))],["Tip per person",money(tip/n(v,"people"))]];},note:"This defaults to calculating the tip on the pre-tax portion. Set tax to zero to tip on the full bill."},
  "sales-tax-calculator": {
    fields:[{key:"amount",label:"Amount",initial:100,suffix:"$",min:0},{key:"rate",label:"Sales tax rate",initial:7,suffix:"%",min:0},{type:"select",key:"mode",label:"Amount entered is",initial:"pre",options:[["pre","Before tax"],["total","Tax-inclusive total"]]}],
    calculate:(v)=>{const rate=n(v,"rate")/100;const subtotal=s(v,"mode")==="pre"?n(v,"amount"):n(v,"amount")/(1+rate);const total=s(v,"mode")==="pre"?n(v,"amount")*(1+rate):n(v,"amount");return [["Subtotal",money(subtotal)],["Sales tax",money(total-subtotal)],["Total",money(total)],["Effective multiplier",number(1+rate,4)]];},note:"Enter the combined rate that applies to the exact location and taxable item. This does not determine nexus, exemptions, or filing obligations."},
  "discount-calculator": {
    fields:[{key:"price",label:"Original price",initial:120,suffix:"$",min:0},{key:"first",label:"First discount",initial:25,suffix:"%",min:0},{key:"second",label:"Additional discount",initial:10,suffix:"%",min:0},{key:"tax",label:"Tax after discount",initial:0,suffix:"%",min:0},{key:"quantity",label:"Quantity",initial:1,min:1,step:1}],
    calculate:(v)=>{const discounted=n(v,"price")*(1-n(v,"first")/100)*(1-n(v,"second")/100);const total=discounted*(1+n(v,"tax")/100)*n(v,"quantity");const saved=(n(v,"price")-discounted)*n(v,"quantity");return [["Price after discounts",money(discounted)],["Combined discount",pct((1-discounted/Math.max(n(v,"price"),.01))*100)],["Savings",money(saved)],["Tax per item",money(discounted*n(v,"tax")/100)],["Final total",money(total)]];},note:"Stacked discounts multiply rather than add. Tax treatment and coupon order vary by store and location."},
  "compound-interest-calculator": {
    fields:[{key:"principal",label:"Starting amount",initial:10000,suffix:"$",min:0},{key:"rate",label:"Annual return",initial:7,suffix:"%",min:-99},{key:"years",label:"Years",initial:20,min:0},{key:"monthly",label:"Monthly contribution",initial:300,suffix:"$",min:0},{key:"compound",label:"Compounds per year",initial:12,min:1,step:1},{key:"inflation",label:"Inflation",initial:2.5,suffix:"%",min:0}],
    calculate:(v)=>{const periods=Math.max(1,n(v,"years")*n(v,"compound"));const r=n(v,"rate")/100/n(v,"compound");const contribution=n(v,"monthly")*12/n(v,"compound");let balance=n(v,"principal");for(let i=0;i<periods;i++)balance=balance*(1+r)+contribution;const contributed=n(v,"principal")+n(v,"monthly")*12*n(v,"years");const real=balance/(1+n(v,"inflation")/100)**n(v,"years");return [["Future balance",money(balance)],["Total contributed",money(contributed)],["Investment growth",money(balance-contributed)],["Inflation-adjusted value",money(real)],["Ending annual growth",money(balance*n(v,"rate")/100)]];},note:"This is a mathematical projection, not an investment forecast. Returns, fees, taxes, timing, and inflation vary and can reduce results."},
  "gpa-calculator": {
    fields:[1,2,3,4,5].flatMap((index)=>[{key:`g${index}`,label:`Course ${index} grade points`,initial:index===1?4:index===2?3.7:index===3?3.3:index===4?3:0,min:0,step:.01},{key:`c${index}`,label:`Course ${index} credits`,initial:index<5?3:0,min:0,step:.5}]),
    calculate:(v)=>{let points=0,credits=0;for(let i=1;i<=5;i++){points+=n(v,`g${i}`)*n(v,`c${i}`);credits+=n(v,`c${i}`);}return [["Weighted grade points",number(points,2)],["Total credits",number(credits,2)],["Semester GPA",number(points/Math.max(credits,.001),3)],["4.0-scale percentage",pct(points/Math.max(credits,.001)/4*100)]];},note:"Enter the grade-point value used by your school. Pass/fail, repeats, weighted classes, and institutional rounding policies may differ."},
  "grade-calculator": {
    fields:[{key:"current",label:"Current grade",initial:84,suffix:"%",min:0},{key:"completed",label:"Course weight completed",initial:75,suffix:"%",min:0},{key:"finalWeight",label:"Remaining exam weight",initial:25,suffix:"%",min:0},{key:"target",label:"Target course grade",initial:88,suffix:"%",min:0},{key:"exam",label:"Expected exam score",initial:90,suffix:"%",min:0}],
    calculate:(v)=>{const projected=(n(v,"current")*n(v,"completed")+n(v,"exam")*n(v,"finalWeight"))/Math.max(n(v,"completed")+n(v,"finalWeight"),.001);const needed=(n(v,"target")*(n(v,"completed")+n(v,"finalWeight"))-n(v,"current")*n(v,"completed"))/Math.max(n(v,"finalWeight"),.001);return [["Projected final grade",pct(projected)],["Exam score needed",pct(needed)],["Current weighted points",number(n(v,"current")*n(v,"completed")/100,2)],["Expected exam points",number(n(v,"exam")*n(v,"finalWeight")/100,2)],["Target is",needed<=100?"Mathematically reachable":"Above 100% without extra credit"]];},note:"Weights should describe the same grading system. Category rules, dropped assignments, extra credit, and instructor rounding can change the official grade."},
};

export const secondCalculatorSlugs = new Set(Object.keys(specs));

export function SecondCalculatorTool({ slug, name }: { slug: string; name: string }) {
  const spec = specs[slug];
  const [values, setValues] = useState<Record<string, string>>(() => Object.fromEntries(spec.fields.map((field) => [field.key, String(field.initial)])));
  const numericValues = useMemo<Values>(() => Object.fromEntries(spec.fields.map((field) => [field.key, field.type === "select" ? values[field.key] : Number(values[field.key]) || 0])), [spec, values]);
  const results = useMemo(() => spec.calculate(numericValues), [numericValues, spec]);
  const report = `${name}\n${results.map(([label,value])=>`${label}: ${value}`).join("\n")}`;
  return <ToolFrame title={name} status="updates live"><div className="calculator-layout"><div className="field-grid">{spec.fields.map((field)=>field.type==="select"?<SelectField key={field.key} label={field.label} value={values[field.key]} onChange={(value)=>setValues((current)=>({...current,[field.key]:value}))} options={field.options}/>:<NumberField key={field.key} label={field.label} value={values[field.key]} onChange={(value)=>setValues((current)=>({...current,[field.key]:value}))} min={field.min} step={field.step} suffix={field.suffix} help={field.help}/>)}</div><div className="result-panel"><span className="result-kicker">Result</span><ResultGrid values={results}/><ActionRow output={report} filename={`${slug}-result.txt`}/></div></div><p className="tool-caution">{spec.note}</p></ToolFrame>;
}
