"use client";
/* eslint-disable react-hooks/exhaustive-deps */

import { useMemo, useState } from "react";
import { ActionRow, copyText, downloadText, SelectField, TextField, ToolFrame } from "./shared";

function parseDelimited(text:string,delimiter:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(char===delimiter&&!quoted){row.push(cell);cell="";}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(value=>value!=="")||row.length>1)rows.push(row);row=[];cell="";}else cell+=char;}if(quoted)throw new Error("The final quoted field is missing a closing quote.");row.push(cell);if(row.some(value=>value!=="")||row.length>1)rows.push(row);return rows;}
function writeDelimited(rows:string[][],delimiter:string){return rows.map(row=>row.map(cell=>/["\r\n]|,|;|\t|\|/.test(cell)||cell.includes(delimiter)?`"${cell.replaceAll('"','""')}"`:cell).join(delimiter)).join("\n");}
const delimiters:Array<[string,string]>=[[",","Comma"],["\t","Tab"],[";","Semicolon"],["|","Pipe"]];

function CsvDelimiterTool({name}:{name:string}){const [input,setInput]=useState('name,city,note\nAna,Miami,"likes commas, too"\nSam,Austin,plain');const [from,setFrom]=useState(","),[to,setTo]=useState("\t");const result=useMemo(()=>{try{const rows=parseDelimited(input,from);return {output:writeDelimited(rows,to),error:""};}catch(error){return {output:"",error:error instanceof Error?error.message:"Could not parse this file."};}},[input,from,to]);return <ToolFrame title={name} status="quoted cells preserved"><div className="field-grid inline-options"><SelectField label="Input delimiter" value={from} onChange={setFrom} options={delimiters}/><SelectField label="Output delimiter" value={to} onChange={setTo} options={delimiters}/></div><div className="editor-grid"><TextField label="Input data" value={input} onChange={setInput} rows={16}/><TextField label="Converted data" value={result.error?result.error:result.output} onChange={()=>{}} rows={16}/></div>{result.error?<div className="error-output">{result.error}</div>:<ActionRow output={result.output} filename={to==="\t"?"converted.tsv":"converted.csv"}/>}<p className="tool-caution">Quoted delimiters, line breaks, and doubled quotes are preserved. Check unusual files with mixed delimiters before replacing the original.</p></ToolFrame>}

type Match={path:string;value:unknown};
function jsonPath(data:unknown,query:string):Match[]{const source=query.trim();if(!source.startsWith("$"))throw new Error("A JSONPath must start with $.");const raw=source.slice(1);const tokens:Array<string|number|"*">=[];const pattern=/\.([A-Za-z_$][\w$-]*)|\[['"]([^'"]+)['"]\]|\[(\d+|\*)\]|\.\*/g;let match:RegExpExecArray|null;let consumed="";while((match=pattern.exec(raw))){if(match.index!==consumed.length)throw new Error(`Unsupported syntax near ${raw.slice(consumed.length)}`);const token=match[1]??match[2]??match[3]??"*";tokens.push(token==="*"?"*":/^\d+$/.test(token)?Number(token):token);consumed+=match[0];}if(consumed.length!==raw.length)throw new Error(`Unsupported syntax near ${raw.slice(consumed.length)}`);let current:Match[]=[{path:"$",value:data}];for(const token of tokens){const next:Match[]=[];for(const item of current){if(token==="*"){if(Array.isArray(item.value))item.value.forEach((value,index)=>next.push({path:`${item.path}[${index}]`,value}));else if(item.value&&typeof item.value==="object")Object.entries(item.value as Record<string,unknown>).forEach(([key,value])=>next.push({path:`${item.path}.${key}`,value}));}else if(typeof token==="number"&&Array.isArray(item.value)&&token<item.value.length)next.push({path:`${item.path}[${token}]`,value:item.value[token]});else if(typeof token==="string"&&item.value&&typeof item.value==="object"&&token in item.value)next.push({path:`${item.path}.${token}`,value:(item.value as Record<string,unknown>)[token]});}current=next;}return current;}
function JsonPathTool({name}:{name:string}){const [json,setJson]=useState('{\n  "store": {\n    "books": [\n      {"title": "Dune", "price": 12},\n      {"title": "Neuromancer", "price": 10}\n    ]\n  }\n}');const [query,setQuery]=useState("$.store.books[*].title");const result=useMemo(()=>{try{const matches=jsonPath(JSON.parse(json),query);return {error:"",matches,output:matches.map(item=>`${item.path}\t${typeof item.value==="string"?item.value:JSON.stringify(item.value)}`).join("\n")};}catch(error){return {error:error instanceof Error?error.message:"Invalid JSON or path",matches:[] as Match[],output:""};}},[json,query]);return <ToolFrame title={name} status="common JSONPath syntax"><label className="field inline-options"><span>JSONPath query</span><input value={query} onChange={(event)=>setQuery(event.target.value)}/><small>Supports dot properties, bracket properties, array indexes, and wildcards.</small></label><div className="editor-grid"><TextField label="JSON input" value={json} onChange={setJson} rows={18}/><label className="field"><span>Matches ({result.matches.length})</span><textarea className="mono-input" rows={18} value={result.error?result.error:result.output} readOnly/></label></div>{result.error?<div className="error-output">{result.error}</div>:<ActionRow output={result.output} filename="jsonpath-matches.txt"/>}</ToolFrame>}

function escapeAttribute(value:string){return value.replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;");}
function HreflangTool({name}:{name:string}){const [input,setInput]=useState("en-US, https://example.com/us/page\nen-GB, https://example.com/uk/page\nes, https://example.com/es/page\nx-default, https://example.com/page");const result=useMemo(()=>{const errors:string[]=[];const entries=input.split(/\r?\n/).map(line=>line.trim()).filter(Boolean).map((line,index)=>{const comma=line.indexOf(",");if(comma<1){errors.push(`Line ${index+1}: use language, URL`);return null;}const lang=line.slice(0,comma).trim(),rawUrl=line.slice(comma+1).trim();if(lang!=="x-default"&&!/^[a-z]{2,3}(?:-[A-Z][a-z]{3})?(?:-[A-Z]{2}|-\d{3})?$/.test(lang))errors.push(`Line ${index+1}: check language, script, or region casing`);let url="";try{const parsed=new URL(rawUrl);if(!/^https?:$/.test(parsed.protocol))throw new Error();url=parsed.href;}catch{errors.push(`Line ${index+1}: enter a full HTTP(S) URL`);}return url?{lang,url}:null;}).filter(Boolean) as Array<{lang:string;url:string}>;const output=errors.length?"":entries.map(item=>`<link rel="alternate" hreflang="${escapeAttribute(item.lang)}" href="${escapeAttribute(item.url)}" />`).join("\n");return {errors,entries,output};},[input]);return <ToolFrame title={name} status="reciprocal set"><TextField label="Language and URL pairs" value={input} onChange={setInput} rows={10}/><small className="block-help">One per line: language-or-language-REGION, full URL</small>{result.errors.length>0&&<div className="error-output">{result.errors.join(" · ")}</div>}<label className="field"><span>Generated link tags</span><textarea className="mono-input" rows={Math.max(8,result.entries.length+2)} value={result.output} readOnly/></label>{!result.errors.length&&<ActionRow output={result.output} filename="hreflang-tags.html"/>}<p className="tool-caution">Every language version should publish the same complete reciprocal set, including a self-reference. Add x-default when a neutral selector or fallback page exists.</p></ToolFrame>}

const romanPairs:Array<[number,string]>=[[1000,"M"],[900,"CM"],[500,"D"],[400,"CD"],[100,"C"],[90,"XC"],[50,"L"],[40,"XL"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]];
function toRoman(value:number){if(!Number.isInteger(value)||value<1||value>3999)throw new Error("Enter a whole number from 1 to 3999.");let left=value,output="";for(const [numberValue,symbol] of romanPairs)while(left>=numberValue){output+=symbol;left-=numberValue;}return output;}
function fromRoman(value:string){const clean=value.trim().toUpperCase();if(!/^[MDCLXVI]+$/.test(clean))throw new Error("Enter Roman numerals using M, D, C, L, X, V, and I.");let total=0,index=0;for(const [numberValue,symbol] of romanPairs)while(clean.slice(index,index+symbol.length)===symbol){total+=numberValue;index+=symbol.length;}if(index!==clean.length||toRoman(total)!==clean)throw new Error("That is not a standard Roman numeral.");return total;}
function RomanTool({name}:{name:string}){const [input,setInput]=useState("2026");const result=useMemo(()=>{try{if(/^\d+$/.test(input.trim())){const value=Number(input);return {error:"",number:String(value),roman:toRoman(value)};}const value=fromRoman(input);return {error:"",number:String(value),roman:toRoman(value)};}catch(error){return {error:error instanceof Error?error.message:"Invalid value",number:"",roman:""};}},[input]);return <ToolFrame title={name} status="1–3999"><label className="field inline-options"><span>Number or Roman numeral</span><input value={input} onChange={(event)=>setInput(event.target.value)}/></label>{result.error?<div className="error-output">{result.error}</div>:<><div className="conversion-result"><strong>{result.number}</strong><span>=</span><strong>{result.roman}</strong></div><ActionRow output={`${result.number} = ${result.roman}`} filename="roman-numeral.txt"/></>}</ToolFrame>}

const small=["zero","one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen"];
const tens=["","","twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety"];
function underThousand(value:number){const parts:string[]=[];if(value>=100){parts.push(`${small[Math.floor(value/100)]} hundred`);value%=100;}if(value>=20){parts.push(tens[Math.floor(value/10)]);if(value%10)parts[parts.length-1]+=`-${small[value%10]}`;}else if(value>0)parts.push(small[value]);return parts.join(" ");}
function integerWords(value:number){if(value===0)return "zero";const scales:[[number,string],[number,string],[number,string],[number,string]]=[[1e12,"trillion"],[1e9,"billion"],[1e6,"million"],[1e3,"thousand"]];const parts:string[]=[];for(const [size,label] of scales)if(value>=size){parts.push(`${underThousand(Math.floor(value/size))} ${label}`);value%=size;}if(value)parts.push(underThousand(value));return parts.join(" ");}
function NumberWordsTool({name}:{name:string}){const [input,setInput]=useState("12345.67"),[currency,setCurrency]=useState(false);const result=useMemo(()=>{const clean=input.replaceAll(",","").trim();if(!/^-?\d+(?:\.\d+)?$/.test(clean))return "Enter a number using digits.";const negative=clean.startsWith("-");const [wholeRaw,decimalRaw=""]=clean.replace("-","").split(".");let whole=Number(wholeRaw);if(!Number.isSafeInteger(whole)||whole>=1e15)return "Use a number below one quadrillion.";let cents=0;if(currency){cents=Math.round(Number(`0.${decimalRaw||0}`)*100);if(cents===100){whole++;cents=0;}if(whole>=1e15)return "Use a number below one quadrillion.";}let output=`${negative?"negative ":""}${integerWords(whole)}`;if(currency)output+=` ${whole===1?"dollar":"dollars"}${cents?` and ${integerWords(cents)} ${cents===1?"cent":"cents"}`:""}`;else if(decimalRaw)output+=` point ${[...decimalRaw].map(digit=>small[Number(digit)]).join(" ")}`;return output;},[input,currency]);return <ToolFrame title={name} status="plain English"><div className="field-grid"><label className="field"><span>Number</span><input value={input} onChange={(event)=>setInput(event.target.value)}/></label><label className="single-check"><input type="checkbox" checked={currency} onChange={(event)=>setCurrency(event.target.checked)}/> Format as dollars and cents</label></div><div className="notice-output words-output">{result}</div><ActionRow output={result} filename="number-in-words.txt"/></ToolFrame>}

function CsvViewerTool({name}:{name:string}){const [input,setInput]=useState("Name,City,Score\nAna,Miami,92\nSam,Austin,88\nLee,Seattle,95"),[delimiter,setDelimiter]=useState(","),[query,setQuery]=useState(""),[sort,setSort]=useState("");const parsed=useMemo(()=>{try{return {rows:parseDelimited(input,delimiter),error:""};}catch(error){return {rows:[] as string[][],error:error instanceof Error?error.message:"Could not parse this file."};}},[input,delimiter]);const headers=parsed.rows[0]||[];const body=useMemo(()=>{let values=parsed.rows.slice(1).filter(row=>!query||row.some(cell=>cell.toLowerCase().includes(query.toLowerCase())));const index=headers.indexOf(sort);if(index>=0)values=[...values].sort((a,b)=>(a[index]||"").localeCompare(b[index]||"",undefined,{numeric:true}));return values.slice(0,500);},[parsed.rows,headers,query,sort]);const choose=(file:File)=>{const reader=new FileReader();reader.onload=()=>setInput(String(reader.result||""));reader.readAsText(file);};return <ToolFrame title={name} status={`${body.length} visible rows`}><div className="csv-viewer-controls"><SelectField label="Delimiter" value={delimiter} onChange={setDelimiter} options={delimiters}/><label className="field"><span>Search rows</span><input value={query} onChange={(event)=>setQuery(event.target.value)}/></label><SelectField label="Sort by" value={sort} onChange={setSort} options={[["","Original order"],...headers.map(header=>[header,header] as [string,string])]}/><label className="plain-button file-button">Open CSV<input className="visually-hidden-file" type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values" onChange={(event)=>{const file=event.target.files?.[0];if(file)choose(file);}}/></label></div><TextField label="CSV data" value={input} onChange={setInput} rows={8}/>{parsed.error?<div className="error-output">{parsed.error}</div>:<div className="csv-table-wrap"><table className="csv-table"><thead><tr>{headers.map((header,index)=><th key={`${header}-${index}`}>{header||`Column ${index+1}`}</th>)}</tr></thead><tbody>{body.map((row,rowIndex)=><tr key={rowIndex}>{headers.map((_,cellIndex)=><td key={cellIndex}>{row[cellIndex]||""}</td>)}</tr>)}</tbody></table></div>}<p className="tool-caution">The viewer displays up to 500 matching rows to keep the page responsive. Your original data stays in this tab.</p></ToolFrame>}

function escapeHtml(value:string){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");}
function inlineMarkdown(value:string){return value.replace(/`([^`]+)`/g,"<code>$1</code>").replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/\*([^*]+)\*/g,"<em>$1</em>").replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" rel="noreferrer">$1</a>');}
function renderMarkdown(value:string){const lines=escapeHtml(value).split(/\r?\n/);const output:string[]=[];let inList=false;for(const line of lines){if(/^[-*] /.test(line)){if(!inList){output.push("<ul>");inList=true;}output.push(`<li>${inlineMarkdown(line.slice(2))}</li>`);continue;}if(inList){output.push("</ul>");inList=false;}const heading=line.match(/^(#{1,6})\s+(.*)$/);if(heading){const level=heading[1].length;output.push(`<h${level}>${inlineMarkdown(heading[2])}</h${level}>`);}else if(/^> /.test(line))output.push(`<blockquote>${inlineMarkdown(line.slice(2))}</blockquote>`);else if(/^---+$/.test(line))output.push("<hr>");else if(line.trim())output.push(`<p>${inlineMarkdown(line)}</p>`);}if(inList)output.push("</ul>");return output.join("\n");}
function MarkdownTool({name}:{name:string}){const [input,setInput]=useState("# Normal note\n\nWrite with **bold**, *emphasis*, and `inline code`.\n\n- Fast\n- Local\n- Easy to copy\n\n[Example link](https://example.com)");const html=useMemo(()=>renderMarkdown(input),[input]);return <ToolFrame title={name} status="safe local preview"><div className="editor-grid markdown-grid"><TextField label="Markdown" value={input} onChange={setInput} rows={20}/><div className="field"><span>Preview</span><div className="markdown-preview" dangerouslySetInnerHTML={{__html:html}}/></div></div><div className="tool-actions"><button className="plain-button" type="button" onClick={()=>copyText(html)}>Copy HTML</button><button className="plain-button" type="button" onClick={()=>downloadText("preview.html",`<!doctype html><meta charset="utf-8"><body>${html}</body>`,"text/html")}>Download HTML</button></div><p className="tool-caution">Raw HTML is escaped. The preview supports headings, paragraphs, lists, blockquotes, rules, bold, emphasis, inline code, and HTTP(S) links.</p></ToolFrame>}

export const secondTextSlugs=new Set(["jsonpath-tester","csv-delimiter-converter","hreflang-tag-generator","roman-numeral-converter","number-to-words-converter","csv-viewer","markdown-preview"]);
export function SecondTextTool({slug,name}:{slug:string;name:string}){switch(slug){case"jsonpath-tester":return <JsonPathTool name={name}/>;case"csv-delimiter-converter":return <CsvDelimiterTool name={name}/>;case"hreflang-tag-generator":return <HreflangTool name={name}/>;case"roman-numeral-converter":return <RomanTool name={name}/>;case"number-to-words-converter":return <NumberWordsTool name={name}/>;case"csv-viewer":return <CsvViewerTool name={name}/>;case"markdown-preview":return <MarkdownTool name={name}/>;default:return null;}}
