import { secondExpansionTools } from "./new-tools";

export type Tool = {
  slug: string;
  name: string;
  symbol: string;
  shortDescription: string;
  category: "Hardware" | "Money" | "Building" | "Files" | "Planning" | "Developer" | "Design" | "Text" | "Names";
  live: boolean;
  demandGroup?: "Opportunity" | "Essential";
  release?: 2;
};

export const tools: Tool[] = [
  { slug: "gamepad-tester", name: "Online Gamepad Tester", symbol: "GP", shortDescription: "Check every button, trigger, stick, and D-pad input live.", category: "Hardware", live: true },
  { slug: "touchscreen-dead-zone-tester", name: "Touchscreen Dead-Zone Tester", symbol: "TZ", shortDescription: "Draw across your screen to find missed touch areas and dead zones.", category: "Hardware", live: true },
  { slug: "camera-shutter-count-checker", name: "Camera Shutter Count Checker", symbol: "SC", shortDescription: "Read the shutter count stored inside an original camera photo.", category: "Hardware", live: true },

  { slug: "etsy-fee-profit-calculator", name: "Etsy Fee & Profit Calculator", symbol: "E$", shortDescription: "See listing, transaction, payment, ad fees, profit, margin, and break-even price.", category: "Money", live: true },
  { slug: "roof-pitch-rafter-calculator", name: "Roof Pitch & Rafter Calculator", symbol: "RF", shortDescription: "Calculate roof pitch, angle, rafter length, and roof area from a few measurements.", category: "Building", live: true },
  { slug: "amazon-fba-profit-calculator", name: "Amazon FBA Profit Calculator", symbol: "FBA", shortDescription: "Estimate Amazon fees, net profit, margin, and ROI for an FBA product.", category: "Money", live: true },
  { slug: "construction-estimate-generator", name: "Construction Estimate Generator", symbol: "CE", shortDescription: "Build a clean labor-and-material estimate and print it as a customer-ready PDF.", category: "Building", live: true },
  { slug: "deck-material-calculator", name: "Deck Material Calculator", symbol: "DK", shortDescription: "Estimate boards, joists, fasteners, and waste for a rectangular deck.", category: "Building", live: true },
  { slug: "bank-statement-pdf-to-csv-converter", name: "Bank Statement PDF-to-CSV Converter", symbol: "CSV", shortDescription: "Extract transaction-like rows from a text-based bank statement PDF into editable CSV.", category: "Files", live: true },
  { slug: "yaml-to-json-converter", name: "YAML-to-JSON Converter", symbol: "YJ", shortDescription: "Turn common YAML documents into formatted JSON without sending code anywhere.", category: "Developer", live: true },
  { slug: "psd-to-png-converter", name: "PSD-to-PNG Converter", symbol: "PSD", shortDescription: "Open a flattened Photoshop preview and export it as a browser-friendly PNG.", category: "Files", live: true },
  { slug: "mp3-to-midi-converter", name: "MP3-to-MIDI Converter", symbol: "MIDI", shortDescription: "Analyze a clear single-note recording and export an experimental MIDI melody.", category: "Files", live: true },
  { slug: "dwg-to-pdf-converter", name: "DWG-to-PDF Converter", symbol: "DWG", shortDescription: "Prepare a local CAD drawing for a clean, printable PDF workflow.", category: "Files", live: true },
  { slug: "stl-to-g-code-converter", name: "STL-to-G-code Converter", symbol: "STL", shortDescription: "Turn an ASCII STL outline into simple preview G-code with basic printer settings.", category: "Files", live: true },
  { slug: "wedding-seating-chart-builder", name: "Wedding Seating Chart Builder", symbol: "WS", shortDescription: "Arrange guests into tables, spot open seats, and print a simple seating plan.", category: "Planning", live: true },
  { slug: "photography-contract-generator", name: "Photography Contract Generator", symbol: "PC", shortDescription: "Draft a plain-language photography agreement from your project details.", category: "Planning", live: true },
  { slug: "bulk-meta-description-generator", name: "Bulk Meta Description Generator", symbol: "MD", shortDescription: "Create consistent, length-checked meta descriptions from pasted page data.", category: "Text", live: true },
  { slug: "regex-tester", name: "Regex Tester", symbol: ".*", shortDescription: "Test JavaScript regular expressions, flags, captures, and replacements live.", category: "Developer", live: true },
  { slug: "base64-encoder", name: "Base64 Encoder", symbol: "64", shortDescription: "Encode or decode Unicode text as Base64 entirely in your browser.", category: "Developer", live: true },
  { slug: "sql-formatter", name: "SQL Formatter", symbol: "SQL", shortDescription: "Make dense SQL readable with practical keyword breaks and indentation.", category: "Developer", live: true },
  { slug: "jwt-decoder", name: "JWT Decoder", symbol: "JWT", shortDescription: "Inspect a JSON Web Token header, payload, and expiry without uploading it.", category: "Developer", live: true },
  { slug: "yaml-validator", name: "YAML Validator", symbol: "YV", shortDescription: "Check common YAML syntax and see an exact line for indentation or mapping errors.", category: "Developer", live: true },
  { slug: "cron-expression-generator", name: "Cron Expression Generator", symbol: "CR", shortDescription: "Build a five-field cron schedule from readable time and date controls.", category: "Developer", live: true },
  { slug: "domain-age-checker", name: "Domain Age Checker", symbol: "AGE", shortDescription: "Look up a domain registration date through public RDAP data and calculate its age.", category: "Developer", live: true },
  { slug: "readability-score-checker", name: "Readability Score Checker", symbol: "RE", shortDescription: "Measure reading ease, grade level, sentence length, and difficult words.", category: "Text", live: true },
  { slug: "text-diff-checker", name: "Text Diff Checker", symbol: "DIFF", shortDescription: "Compare two blocks line by line and highlight additions, removals, and changes.", category: "Text", live: true },
  { slug: "robots-txt-generator", name: "Robots.txt Generator", symbol: "BOT", shortDescription: "Build a conservative robots.txt file with sitemap and crawler controls.", category: "Developer", live: true },
  { slug: "uuid-generator", name: "UUID Generator", symbol: "ID", shortDescription: "Generate one or hundreds of cryptographically random UUID v4 identifiers.", category: "Developer", live: true },
  { slug: "hash-generator", name: "Hash Generator", symbol: "#", shortDescription: "Create SHA-1, SHA-256, SHA-384, or SHA-512 hashes with Web Crypto.", category: "Developer", live: true },
  { slug: "favicon-generator", name: "Favicon Generator", symbol: "ICO", shortDescription: "Make square favicon PNGs from a letter, emoji, color, or uploaded image.", category: "Design", live: true },
  { slug: "color-picker", name: "Color Picker", symbol: "RGB", shortDescription: "Pick a color and copy matching HEX, RGB, and HSL values.", category: "Design", live: true },
  { slug: "css-gradient-generator", name: "CSS Gradient Generator", symbol: "CSS", shortDescription: "Build a two-color CSS gradient visually and copy production-ready code.", category: "Design", live: true },
  { slug: "code-beautifier", name: "Code Beautifier", symbol: "{ }", shortDescription: "Re-indent common JSON, JavaScript, CSS, HTML, XML, and SQL snippets.", category: "Developer", live: true },
  { slug: "xml-formatter", name: "XML Formatter", symbol: "XML", shortDescription: "Validate and indent XML while preserving element order and attributes.", category: "Developer", live: true },
  { slug: "url-encoder", name: "URL Encoder", symbol: "%", shortDescription: "Encode or decode URL components, query values, and full pasted strings.", category: "Developer", live: true },
  { slug: "html-encoder", name: "HTML Encoder", symbol: "&;", shortDescription: "Escape HTML special characters or turn entities back into readable text.", category: "Developer", live: true },
  { slug: "html-minifier", name: "HTML Minifier", symbol: "H−", shortDescription: "Remove safe whitespace and comments from HTML and compare byte savings.", category: "Developer", live: true },
  { slug: "css-minifier", name: "CSS Minifier", symbol: "C−", shortDescription: "Compress CSS whitespace and comments for a smaller production file.", category: "Developer", live: true },
  { slug: "javascript-minifier", name: "JavaScript Minifier", symbol: "J−", shortDescription: "Apply conservative whitespace and comment removal to simple JavaScript.", category: "Developer", live: true },
  { slug: "slug-generator", name: "Slug Generator", symbol: "SL", shortDescription: "Turn titles or whole lists into clean lowercase URL slugs.", category: "Text", live: true },
  { slug: "px-to-rem-converter", name: "PX-to-REM Converter", symbol: "REM", shortDescription: "Convert pixels and rem values using any root font size.", category: "Design", live: true },
  { slug: "hex-to-rgb-converter", name: "HEX-to-RGB Converter", symbol: "HEX", shortDescription: "Convert HEX colors to RGB, RGBA, and CSS custom property values.", category: "Design", live: true },
  { slug: "timestamp-converter", name: "Timestamp Converter", symbol: "TS", shortDescription: "Convert Unix seconds, milliseconds, ISO dates, local time, and UTC.", category: "Developer", live: true },
  { slug: "aspect-ratio-calculator", name: "Aspect Ratio Calculator", symbol: "16:9", shortDescription: "Find a ratio or calculate the missing width or height without distortion.", category: "Design", live: true },
  { slug: "case-converter", name: "Case Converter", symbol: "Aa", shortDescription: "Switch text among upper, lower, title, sentence, camel, snake, and kebab case.", category: "Text", live: true },
  { slug: "binary-converter", name: "Binary Converter", symbol: "01", shortDescription: "Convert text, binary, decimal bytes, and hexadecimal in either direction.", category: "Developer", live: true },
  { slug: "character-counter", name: "Character Counter", symbol: "#C", shortDescription: "Count characters, spaces, lines, bytes, words, and social-post limits live.", category: "Text", live: true },
  { slug: "word-counter", name: "Word Counter", symbol: "#W", shortDescription: "Count words, paragraphs, sentences, reading time, and speaking time live.", category: "Text", live: true },
  { slug: "twitch-bits-to-usd-converter", name: "Twitch Bits-to-USD Converter", symbol: "BITS", shortDescription: "Convert Twitch Bits to the standard creator payout value in US dollars.", category: "Money", live: true },
  { slug: "podcast-name-generator", name: "Podcast Name Generator", symbol: "POD", shortDescription: "Generate focused, memorable podcast names from a topic and tone.", category: "Names", live: true },
  { slug: "band-name-generator", name: "Band Name Generator", symbol: "BND", shortDescription: "Generate band names by genre, mood, and naming style.", category: "Names", live: true },
  { slug: "dnd-name-generator", name: "D&D Name Generator", symbol: "D20", shortDescription: "Create fantasy character names by ancestry and style for tabletop games.", category: "Names", live: true },
  { slug: "clan-name-generator", name: "Clan Name Generator", symbol: "GG", shortDescription: "Generate short, usable clan names and tags by game style.", category: "Names", live: true },

  { slug: "ebay-fee-profit-calculator", name: "eBay Fee & Profit Calculator", symbol: "EB", shortDescription: "Estimate eBay selling fees, costs, profit, margin, and break-even price.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "depop-fee-calculator", name: "Depop Fee Calculator", symbol: "DP", shortDescription: "Estimate Depop fees and net profit with editable marketplace rates.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "poshmark-fee-calculator", name: "Poshmark Fee Calculator", symbol: "PM", shortDescription: "Calculate a Poshmark sale payout, costs, and profit margin.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "mercari-profit-calculator", name: "Mercari Profit Calculator", symbol: "MC", shortDescription: "Estimate Mercari selling fees and the profit left after product and shipping costs.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "whatnot-seller-fee-calculator", name: "Whatnot Seller Fee Calculator", symbol: "WN", shortDescription: "Estimate Whatnot commission, payment fees, seller payout, and profit.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "tiktok-shop-fee-calculator", name: "TikTok Shop Fee Calculator", symbol: "TT", shortDescription: "Estimate TikTok Shop referral fees, seller costs, and net margin.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "gumroad-fee-calculator", name: "Gumroad Fee Calculator", symbol: "GR", shortDescription: "Calculate Gumroad fees and net earnings for a digital product sale.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "patreon-earnings-calculator", name: "Patreon Earnings Calculator", symbol: "PT", shortDescription: "Estimate Patreon platform and payment fees from monthly membership revenue.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "kdp-royalty-calculator", name: "KDP Royalty Calculator", symbol: "KDP", shortDescription: "Estimate Kindle or paperback royalty after delivery or printing costs.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "printify-profit-calculator", name: "Printify Profit Calculator", symbol: "PF", shortDescription: "Calculate print-on-demand profit after production, shipping, and storefront fees.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "shopify-profit-margin-calculator", name: "Shopify Profit Margin Calculator", symbol: "SH", shortDescription: "Estimate order profit after product, shipping, payment, ad, and app costs.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "stripe-fee-calculator", name: "Stripe Fee Calculator", symbol: "ST", shortDescription: "Calculate Stripe processing fees, net payout, or the amount to charge.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "paypal-fee-calculator", name: "PayPal Fee Calculator", symbol: "PP", shortDescription: "Estimate PayPal fees, take-home amount, and reverse fee gross-up.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "square-fee-calculator", name: "Square Fee Calculator", symbol: "SQ", shortDescription: "Calculate Square payment fees and the net amount from a transaction.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "airbnb-host-payout-calculator", name: "Airbnb Host Payout Calculator", symbol: "AB", shortDescription: "Estimate a host payout after service fees, cleaning, taxes, and operating costs.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "fence-material-calculator", name: "Fence Material Calculator", symbol: "FN", shortDescription: "Estimate fence panels, posts, rails, pickets, and concrete from a run length.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "concrete-bag-calculator", name: "Concrete Bag Calculator", symbol: "CB", shortDescription: "Find concrete volume and the number of premix bags needed for a slab.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "gravel-calculator", name: "Gravel Calculator", symbol: "GV", shortDescription: "Estimate cubic yards and tons of gravel from area, depth, and density.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "mulch-calculator", name: "Mulch Calculator", symbol: "MU", shortDescription: "Calculate mulch volume in cubic yards and bags for a landscape bed.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "wallpaper-roll-calculator", name: "Wallpaper Roll Calculator", symbol: "WR", shortDescription: "Estimate wallpaper strips and rolls while allowing for pattern repeat and waste.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "tile-calculator-with-waste", name: "Tile Calculator with Waste", symbol: "TL", shortDescription: "Calculate tile area, piece count, boxes, and a realistic waste allowance.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "drywall-sheet-calculator", name: "Drywall Sheet Calculator", symbol: "DR", shortDescription: "Estimate drywall sheets, screws, joint compound, and tape for a room.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "paint-calculator", name: "Paint Calculator", symbol: "PA", shortDescription: "Estimate gallons of primer and paint from wall area, coats, and coverage.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "sod-calculator", name: "Sod Calculator", symbol: "SOD", shortDescription: "Calculate sod square footage, rolls, pallets, and waste for a lawn.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "stair-stringer-calculator", name: "Stair Stringer Calculator", symbol: "SR", shortDescription: "Find riser count, exact rise, total run, stringer length, and stair angle.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "board-foot-calculator", name: "Board Foot Calculator", symbol: "BF", shortDescription: "Calculate lumber board feet, total volume, and cost for multiple pieces.", category: "Building", live: true, demandGroup: "Opportunity" },
  { slug: "pallet-loading-calculator", name: "Pallet Loading Calculator", symbol: "PL", shortDescription: "Estimate cartons per layer, total cartons, loaded height, and gross weight.", category: "Planning", live: true, demandGroup: "Opportunity" },
  { slug: "shipping-dimensional-weight-calculator", name: "Shipping Dimensional Weight Calculator", symbol: "DIM", shortDescription: "Compare actual and dimensional package weight for common carrier divisors.", category: "Planning", live: true, demandGroup: "Opportunity" },
  { slug: "aquarium-volume-calculator", name: "Aquarium Volume Calculator", symbol: "AQ", shortDescription: "Calculate aquarium gallons, liters, water weight, and substrate volume.", category: "Planning", live: true, demandGroup: "Opportunity" },
  { slug: "generator-wattage-calculator", name: "Generator Wattage Calculator", symbol: "W", shortDescription: "Estimate running watts, startup surge, and a safe generator size.", category: "Hardware", live: true, demandGroup: "Opportunity" },
  { slug: "solar-panel-output-calculator", name: "Solar Panel Output Calculator", symbol: "SUN", shortDescription: "Estimate daily and monthly solar energy from panel size, sun hours, and losses.", category: "Hardware", live: true, demandGroup: "Opportunity" },
  { slug: "ev-charging-cost-calculator", name: "EV Charging Cost Calculator", symbol: "EV", shortDescription: "Calculate home charging cost, cost per mile, and monthly electricity use.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "battery-runtime-calculator", name: "Battery Runtime Calculator", symbol: "BAT", shortDescription: "Estimate usable battery energy and runtime from voltage, amp-hours, and load.", category: "Hardware", live: true, demandGroup: "Opportunity" },
  { slug: "tv-viewing-distance-calculator", name: "TV Viewing Distance Calculator", symbol: "TV", shortDescription: "Find a comfortable viewing distance range from television size and resolution.", category: "Hardware", live: true, demandGroup: "Opportunity" },
  { slug: "screen-ppi-calculator", name: "Screen PPI Calculator", symbol: "PPI", shortDescription: "Calculate pixel density, pixel pitch, and physical screen dimensions.", category: "Hardware", live: true, demandGroup: "Opportunity" },
  { slug: "sewing-fabric-yardage-calculator", name: "Sewing Fabric Yardage Calculator", symbol: "YD", shortDescription: "Estimate fabric yardage from piece dimensions, quantity, width, and waste.", category: "Planning", live: true, demandGroup: "Opportunity" },
  { slug: "coffee-ratio-calculator", name: "Coffee Ratio Calculator", symbol: "CF", shortDescription: "Calculate coffee and water amounts for any brew ratio or serving size.", category: "Planning", live: true, demandGroup: "Opportunity" },
  { slug: "pizza-dough-calculator", name: "Pizza Dough Calculator", symbol: "PZ", shortDescription: "Calculate flour, water, salt, and yeast for any number of dough balls.", category: "Planning", live: true, demandGroup: "Opportunity" },
  { slug: "bread-hydration-calculator", name: "Bread Hydration Calculator", symbol: "BH", shortDescription: "Calculate baker’s percentages, dough hydration, and total dough weight.", category: "Planning", live: true, demandGroup: "Opportunity" },
  { slug: "recipe-cost-calculator", name: "Recipe Cost Calculator", symbol: "RC", shortDescription: "Estimate batch cost, cost per serving, target price, and food-cost percentage.", category: "Money", live: true, demandGroup: "Opportunity" },
  { slug: "chmod-calculator", name: "Chmod Calculator", symbol: "755", shortDescription: "Build Unix file permissions and copy octal, symbolic, and chmod output.", category: "Developer", live: true, demandGroup: "Opportunity" },
  { slug: "cidr-calculator", name: "CIDR Calculator", symbol: "/24", shortDescription: "Calculate IPv4 network range, subnet mask, broadcast address, and host count.", category: "Developer", live: true, demandGroup: "Opportunity" },
  { slug: "subnet-calculator", name: "Subnet Calculator", symbol: "NET", shortDescription: "Split an IPv4 network into smaller subnets and inspect their address ranges.", category: "Developer", live: true, demandGroup: "Opportunity" },
  { slug: "utm-link-builder", name: "UTM Link Builder", symbol: "UTM", shortDescription: "Build a properly encoded campaign URL from source, medium, campaign, and content.", category: "Developer", live: true, demandGroup: "Opportunity" },
  { slug: "csp-header-generator", name: "CSP Header Generator", symbol: "CSP", shortDescription: "Generate a Content-Security-Policy header from practical resource controls.", category: "Developer", live: true, demandGroup: "Opportunity" },
  { slug: "nginx-redirect-generator", name: "Nginx Redirect Generator", symbol: "301", shortDescription: "Turn old and new paths into safe nginx redirect rules in bulk.", category: "Developer", live: true, demandGroup: "Opportunity" },
  { slug: "json-to-csv-converter", name: "JSON-to-CSV Converter", symbol: "J→C", shortDescription: "Convert an array of JSON objects into escaped CSV with automatic headers.", category: "Developer", live: true, demandGroup: "Opportunity" },
  { slug: "csv-to-json-converter", name: "CSV-to-JSON Converter", symbol: "C→J", shortDescription: "Parse comma-separated rows into formatted JSON objects in your browser.", category: "Developer", live: true, demandGroup: "Opportunity" },
  { slug: "markdown-table-generator", name: "Markdown Table Generator", symbol: "MDT", shortDescription: "Turn CSV, tabs, or pasted rows into a clean Markdown table.", category: "Text", live: true, demandGroup: "Opportunity" },
  { slug: "remove-duplicate-lines-online", name: "Remove Duplicate Lines Online", symbol: "DED", shortDescription: "Remove repeated lines while preserving order, with trim and case options.", category: "Text", live: true, demandGroup: "Opportunity" },

  { slug: "password-generator", name: "Password Generator", symbol: "PW", shortDescription: "Generate secure passwords with adjustable length, character sets, and ambiguity rules.", category: "Developer", live: true, demandGroup: "Essential" },
  { slug: "qr-code-generator", name: "QR Code Generator", symbol: "QR", shortDescription: "Create and download a QR code for text or a URL.", category: "Design", live: true, demandGroup: "Essential" },
  { slug: "bmi-calculator", name: "BMI Calculator", symbol: "BMI", shortDescription: "Calculate body mass index from metric or US measurements with standard ranges.", category: "Planning", live: true, demandGroup: "Essential" },
  { slug: "age-calculator", name: "Age Calculator", symbol: "AGE", shortDescription: "Calculate exact age in years, months, days, total days, and the next birthday.", category: "Planning", live: true, demandGroup: "Essential" },
  { slug: "percentage-calculator", name: "Percentage Calculator", symbol: "%", shortDescription: "Solve common percentage, increase, decrease, and percent-change questions.", category: "Planning", live: true, demandGroup: "Essential" },
  { slug: "loan-calculator", name: "Loan Calculator", symbol: "LN", shortDescription: "Calculate monthly payment, total interest, and total cost for a fixed loan.", category: "Money", live: true, demandGroup: "Essential" },
  { slug: "mortgage-calculator", name: "Mortgage Calculator", symbol: "MTG", shortDescription: "Estimate principal, interest, taxes, insurance, and monthly housing payment.", category: "Money", live: true, demandGroup: "Essential" },
  { slug: "calorie-calculator", name: "Calorie Calculator", symbol: "CAL", shortDescription: "Estimate daily calorie needs from age, body measurements, sex, and activity.", category: "Planning", live: true, demandGroup: "Essential" },
  { slug: "unit-converter", name: "Unit Converter", symbol: "UNI", shortDescription: "Convert common length, weight, temperature, area, volume, and speed units.", category: "Planning", live: true, demandGroup: "Essential" },
  { slug: "image-resizer", name: "Image Resizer", symbol: "IMG", shortDescription: "Resize an image to exact pixel dimensions while optionally preserving its ratio.", category: "Files", live: true, demandGroup: "Essential" },
  { slug: "image-compressor", name: "Image Compressor", symbol: "CMP", shortDescription: "Compress JPEG or WebP images locally with a visual quality and size comparison.", category: "Files", live: true, demandGroup: "Essential" },
  { slug: "jpg-to-png-converter", name: "JPG-to-PNG Converter", symbol: "JPG", shortDescription: "Convert JPEG images into lossless PNG files without uploading them.", category: "Files", live: true, demandGroup: "Essential" },
  { slug: "png-to-jpg-converter", name: "PNG-to-JPG Converter", symbol: "PNG", shortDescription: "Convert PNG images to smaller JPEG files with a chosen background and quality.", category: "Files", live: true, demandGroup: "Essential" },
  { slug: "pdf-merger", name: "PDF Merger", symbol: "PDF+", shortDescription: "Combine multiple PDF files in order and download one merged document locally.", category: "Files", live: true, demandGroup: "Essential" },
  { slug: "pdf-splitter", name: "PDF Splitter", symbol: "PDF÷", shortDescription: "Extract a page range or split every PDF page into separate documents.", category: "Files", live: true, demandGroup: "Essential" },
  { slug: "json-formatter", name: "JSON Formatter", symbol: "JSON", shortDescription: "Validate, indent, minify, sort, and copy JSON in a focused editor.", category: "Developer", live: true, demandGroup: "Essential" },
  { slug: "json-validator", name: "JSON Validator", symbol: "JV", shortDescription: "Check JSON syntax and locate the parse error without sending data anywhere.", category: "Developer", live: true, demandGroup: "Essential" },
  { slug: "lorem-ipsum-generator", name: "Lorem Ipsum Generator", symbol: "LI", shortDescription: "Generate placeholder paragraphs, sentences, or words with plain copy output.", category: "Text", live: true, demandGroup: "Essential" },
  { slug: "random-number-generator", name: "Random Number Generator", symbol: "RNG", shortDescription: "Generate unique or repeated random integers within any range.", category: "Planning", live: true, demandGroup: "Essential" },
  { slug: "time-zone-converter", name: "Time Zone Converter", symbol: "TZ", shortDescription: "Compare a date and time across major IANA time zones with daylight saving handled.", category: "Planning", live: true, demandGroup: "Essential" },
  ...secondExpansionTools,
];

export const addedTools = tools.slice(3);
export const newestTools = tools.slice(123);

export function getTool(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}
